'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'ru' | 'uk' | 'en' | 'es' | 'it' | 'fr';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  name: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'ru', label: 'RU', name: 'Русский', flag: '/images/flags/ru.svg' },
  { code: 'en', label: 'EN', name: 'English', flag: '/images/flags/en.svg' },
  { code: 'uk', label: 'UA', name: 'Українська', flag: '/images/flags/ua.svg' },
  { code: 'es', label: 'ES', name: 'Español', flag: '/images/flags/es.svg' },
  { code: 'it', label: 'IT', name: 'Italiano', flag: '/images/flags/it.svg' },
  { code: 'fr', label: 'FR', name: 'Français', flag: '/images/flags/fr.svg' },
];

export const TRANSLATIONS: Record<LanguageCode, any> = {
  ru: {
    nav: {
      services: 'Услуги',
      usaGreenCard: 'США & GREEN CARD',
      jurisdictions: 'Юрисдикции',
      about: 'О практике',
      faq: 'Частые вопросы',
      contacts: 'Контакты',
      bookConsultation: 'Консультация',
      langTitle: 'Язык / Language',
    },
    headerDropdown: {
      examTitle: 'Подготовка к экзамену на гражданство',
      examDesc: '100 вопросов по истории и государственному устройству США, языковой тренинг',
      examTag: 'Экзамен',
      talentTitle: 'Визы талантов (EB-1A / EB-2 NIW)',
      talentDesc: 'Оформление грин-карты без американского работодателя для профессионалов',
      talentTag: 'EB-1A',
      interviewTitle: 'Консульское интервью и безопасность',
      interviewDesc: 'Стресс-интервью, проверка биографии и алгоритмы защиты статуса',
      interviewTag: 'Консул',
      corpTitle: 'Корпоративное и налоговое право',
      corpDesc: 'Регистрация Delaware, Wyoming, структурирование владения',
      corpTag: 'Бизнес',
    },
    hero: {
      badge: 'МЕЖДУНАРОДНАЯ ЮРИДИЧЕСКАЯ ПОМОЩЬ',
      title1: 'Ваши права —',
      title2: 'без границ',
      desc: 'Профессиональная юридическая поддержка для людей и бизнеса в США и по всему миру.',
      flow1: 'Сложная ситуация',
      flow2: 'Точный анализ',
      flow3: 'Стратегия',
      flow4: 'Решение',
      badgeNy: '15 лет в Нью-Йорке',
      badgeCitizen: 'Гражданин США',
      ctaConsultation: 'Стратегическая консультация',
      ctaUsa: 'Практика США & Green Card',
    },
    services: {
      title1: 'Международные юридические решения',
      title2: 'высокой точности',
      desc: 'Частная юридическая практика для кейсов повышенной сложности в США и глобальных финансовых центрах. Глубокий анализ федеральной правовой системы, нестандартная стратегия и построчная защита интересов доверителя.',
      btnAll: 'Все направления практики',
      c1Title: 'США: Green Card & Гражданство',
      c1Code: '#ИММИГРАЦИЯ & GREEN CARD',
      c1Desc: 'Индивидуальная стратегия получения статуса резидента США: визы талантов EB-1A, национальные интересы EB-2 NIW, смена статуса и подготовка к получению гражданства США.',
      c2Title: 'Международный бизнес и трансграничные контракты',
      c2Code: '#МЕЖДУНАРОДНЫЙ БИЗНЕС',
      c2Desc: 'Корпоративное структурирование в США (Delaware, Wyoming), Великобритании, ЕС и ОАЭ (DIFC / ADGM). Международные контракты и комплаенс.',
      c3Title: 'Защита частных активов, фонды и трасты',
      c3Code: '#ЗАЩИТА АКТИВОВ & ТРАСТЫ',
      c3Desc: 'Формирование безотзывных международных трастов, защита капитала от притязаний, безопасное владение активами и трансграничная налоговая защита.',
      c4Title: 'Трансграничные судебные споры и арбитраж',
      c4Code: '#АРБИТРАЖ & СУДЫ',
      c4Desc: 'Защита интересов частных лиц и компаний в международных коммерческих конфликтах, арбитраж и признание судебных решений в иностранных юрисдикциях.',
      c5Title: 'Аудит юридических рисков и Due Diligence',
      c5Code: '#АУДИТ РИСКОВ',
      c5Desc: 'Построчный юридический аудит документов до их подписания: выявление ловушек, проверка контрагентов, аудит иммиграционных кейсов и договоров.',
      c6Title: 'Индивидуальная трансграничная стратегия',
      c6Code: '#СТРАТЕГИЯ',
      c6Desc: 'Комплексный юридический маршрут для нестандартных ситуаций на стыке американского и международного права по принципу Analyze → Strategize → Act.',
    },
    greenCard: {
      badge: 'ФЛАГМАНСКАЯ АМЕРИКАНСКАЯ ПРАКТИКА',
      title1: 'США: Иммиграция, Гражданство',
      title2: 'и Защита статуса',
      desc: '15 лет в Нью-Йорке. Персональная стратегия, построчный аудит заявления N-400, проработка 128 вопросов Civics Test и снятие процессуальных рисков.',
      btnTest: 'Пройти тест на иммиграцию',
      btnInterview: 'Консульское интервью',
      c1Title: 'Green Card & Иммиграция',
      c1Desc: 'Индивидуальная стратегия получения статуса резидента: визы талантов EB-1A / EB-2 NIW, смена статуса и семейные петиции.',
      c1Tag: 'Популярное',
      c2Title: 'Гражданство США',
      c2Desc: 'Комплексный юридический трекинг заявителя до принятия присяги и получения американского паспорта.',
      c2Tag: 'Флагман',
      c3Title: 'Civics Test 2026',
      c3Desc: 'Подготовка к актуальному тесту 2026 года на 128 вопросов: история США, Конституция, устройство органов власти и языковой минимум.',
      c3Tag: '2026 Test',
      c4Title: 'Подготовка к интервью USCIS',
      c4Desc: 'Репетиция стресс-собеседований с американским офицером: что спрашивают, как отвечать и как устранить двусмысленности.',
      c4Tag: 'Mock Interview',
      c5Title: 'Аудит заявления N-400',
      c5Desc: 'Построчный юридический разбор анкеты N-400 на гражданство США до её подачи для исключения скрытых процессуальных ловушек.',
      c5Tag: 'Аудит рисков',
      c6Title: 'Индивидуальный аудит и стратегия',
      c6Desc: 'Персональная оценка шансов на гражданство или Green Card с моделированием критических зон вашего дела.',
      c6Tag: 'Bespoke',
      gc1Code: '#GREEN CARD',
      gc2Code: '#ГРАЖДАНСТВО США',
      gc3Code: '#CIVICS TEST 2026',
      gc4Code: '#ИНТЕРВЬЮ USCIS',
      gc5Code: '#АУДИТ N-400',
      gc6Code: '#ПРАВОВАЯ СТРАТЕГИЯ',
      stageTitle: '7 этапов подготовки к получению гражданства США',
      s1Title: 'Анализ N-400',
      s1Desc: 'Построчный разбор анкеты и выявление потенциально проблемных мест до отправки.',
      s2Title: 'Вопросы офицера',
      s2Desc: 'Что спрашивает офицер, как корректно формулировать ответы по вашей ситуации.',
      s3Title: '2026 Civics Test',
      s3Desc: 'Отработка 128 вопросов по истории и устройству США (до 20 задают, 12 для зачета).',
      s4Title: 'English Component',
      s4Desc: 'Чтение, письмо и разговорный блок: формулировки, снимающие сомнения офицера.',
      s5Title: 'N-400 Audit',
      s5Desc: 'Выявление «красных флагов» в биографии, поездках и налогах до подачи.',
      s6Title: 'Симуляция интервью',
      s6Desc: 'Моделирование реального собеседования в формате стресс-теста с разбором ошибок.',
      s7Title: 'Финальная готовность',
      s7Desc: 'Пакет документов, стратегия поведения и чек-лист для дня присяги.',
      ctaAudit: 'Начать персональный аудит',
      ctaTest: 'Открыть интерактивный Civics Test',
    },
    about: {
      title1: 'Международные юридические решения',
      title2: 'высокой точности',
      desc: 'Частная юридическая практика для кейсов повышенной сложности в США и глобальных финансовых центрах. Глубокий анализ федеральной правовой системы, нестандартная стратегия и построчная защита интересов доверителя.',
      p1Title: '15+ лет практики в США',
      p1Desc: 'Глубокая экспертиза в федеральном праве и USCIS. Личный статус гражданина США, опыт ведения комплексных иммиграционных кейсов.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Строгая конфиденциальность',
      p2Desc: 'Институциональная конфиденциальность по стандарту Attorney-Client Privilege. Полная защита данных, документов и активов.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Синхронизация юрисдикций',
      p3Desc: 'Трансграничное структурирование: США (Delaware, Wyoming), ЕС, Великобритания и ОАЭ (DIFC). Нивелирование налоговых коллизий.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Методология Analyze → Act',
      p4Desc: 'Построчный превентивный аудит юридических рисков до подачи любых форм. Выверенная пошаговая дорожная карта защиты интересов.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Подробнее о принципах практики',
    },
    countries: {
      badge: 'ГЕОГРАФИЯ И ПРАВОВЫЕ СИСТЕМЫ',
      title1: 'Международные юрисдикции',
      title2: 'практики',
      desc: 'Компетенции на стыке нескольких правовых систем. Мы синхронизируем процессуальные нормы разных стран для защиты ваших интересов.',
      btnAll: 'Все юрисдикции',
      hub1Name: 'США',
      hub1Badge: 'Ключевой фокус',
      hub1System: 'Федеральное право США & Право штатов',
      hub1Desc: 'Иммиграционный трекинг (EB-1A / NIW / Гражданство), корпоративное право Delaware и Wyoming, федеральный арбитраж и защита статуса.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'ОАЭ (DIFC / ADGM)',
      hub2Badge: 'Трансграничный хаб',
      hub2System: 'DIFC Courts & English Common Law',
      hub2Desc: 'Структурирование международных компаний, релокация капитала, семейные офисы и защита активов в финансовой юрисдикции Дубая.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'Великобритания',
      hub3Badge: 'Английское право',
      hub3System: 'English Common Law',
      hub3Desc: 'Коммерческие контракты по английскому праву, лондонский арбитраж, структурирование владения недвижимостью и трансграничные трасты.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'Европейский Союз (ЕС)',
      hub4Badge: 'Европейское право',
      hub4System: 'Civil Law & Регламенты ЕС',
      hub4Desc: 'Юридическое сопровождение в Германии, Франции, на Кипре и в Испании. Корпоративный комплаенс, санкционные риски и трансграничные активы.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'КОРИДОР:',
    },
    quote: {
      text: '«Право — это не только законы. Это возможность жить там, где вы хотите.»',
      author: 'V. I. Levin',
    },
    footer: {
      manifesto: 'Международная юридическая практика для сложных задач. Защита интересов частных доверителей и бизнеса без границ и географических барьеров.',
      col1: 'Направления',
      s1: 'Иммиграция и Green Card',
      s2: 'Правовой аудит',
      s3: 'Корпоративное право',
      s4: 'Международные контракты',
      s5: 'Семейное и наследственное',
      s6: 'Судебные споры',
      col2: 'США и Страны',
      u1: 'Green Card США (EB-1 / NIW)',
      u2: 'Консульское интервью',
      u3: 'Тест на иммиграцию',
      u4: 'Юрисдикция США',
      u5: 'Германия и ЕС',
      u6: 'ОАЭ (Дубай / Абу-Даби)',
      u7: 'Кипр (Common Law)',
      col3: 'Практика',
      p1: 'Анонимизированные кейсы',
      p2: 'Статьи и правовой анализ',
      p3: 'Манифест конфиденциальности',
      p4: 'Контакты',
      p5: 'Внутренний реестр',
      disclaimerTitle: 'Юридический дисклеймер и ограничения ответственности:',
      disclaimerText: 'Материалы, опубликованные на данном сайте, носят исключительно информационно-аналитический характер и не являются индивидуальной юридической консультацией или прямым предложением юридических услуг в юрисдикциях, где деятельность требует специальной государственной аккредитации. Мы не даем обещаний 100% гарантии положительного исхода дел и не используем формулировки «гарантия получения визы или Green Card». В случаях, требующих судебного представительства в конкретных национальных судах, привлекаются локальные лицензированные адвокаты соответствующей коллегии (Bar Association / Rechtsanwaltskammer).',
      rights: 'Все права защищены.',
      motto: '«Ваши права — без границ.»',
    },
    modal: {
      title: 'Стратегическая консультация',
      badge: 'ATTORNEY-CLIENT PRIVILEGE · СТРОГО КОНФИДЕНЦИАЛЬНО',
      catUsa: 'США & Green Card',
      catBiz: 'Бизнес & Контракты',
      catDisp: 'Споры & Арбитраж',
      catWealth: 'Активы & Трасты',
      catOther: 'Иные вопросы',
      contactLabel: 'Ваш контакт для обратной связи *',
      contactPlaceholder: '@username в Telegram или телефон / WhatsApp',
      noteLabel: 'Суть вопроса или комментарий',
      notePlaceholder: 'Опишите ключевые обстоятельства, юрисдикции или дедлайны...',
      submitBtn: 'Отправить заявку',
      submitting: 'Отправка заявки...',
      successTitle: 'Заявка принята',
      successDesc: 'Правовой департамент V. I. Levin уведомлен. Мы свяжемся с вами в течение 15 минут.',
      successBtn: 'Закрыть',
      directTg: 'Или напишите напрямую в Telegram-бот:',
      errorRequired: 'Пожалуйста, укажите ваш Telegram, телефон или WhatsApp для связи.',
    },
  },

  en: {
    nav: {
      services: 'Services',
      usaGreenCard: 'USA & GREEN CARD',
      jurisdictions: 'Jurisdictions',
      about: 'About Practice',
      faq: 'FAQ',
      contacts: 'Contacts',
      bookConsultation: 'Consultation',
      langTitle: 'Language',
    },
    headerDropdown: {
      examTitle: 'Citizenship Exam Preparation',
      examDesc: '100 USCIS history & civics questions, English speech training',
      examTag: 'Exam',
      talentTitle: 'Talent Visas (EB-1A / EB-2 NIW)',
      talentDesc: 'Green Card without employer sponsorship for professionals',
      talentTag: 'EB-1A',
      interviewTitle: 'Consular Interview & Security',
      interviewDesc: 'Background checks, cross-questioning simulations',
      interviewTag: 'Consul',
      corpTitle: 'Corporate & Federal Tax Law',
      corpDesc: 'Delaware & Wyoming registration, asset structuring',
      corpTag: 'Business',
    },
    hero: {
      badge: 'INTERNATIONAL LEGAL PRACTICE',
      title1: 'Your rights —',
      title2: 'without borders',
      desc: 'Professional legal counsel and institutional defense for individuals and businesses in the US and worldwide.',
      flow1: 'Complex Case',
      flow2: 'Deep Analysis',
      flow3: 'Strategy',
      flow4: 'Protected Solution',
      badgeNy: '15 Years in New York',
      badgeCitizen: 'U.S. Citizen',
      ctaConsultation: 'Strategic Consultation',
      ctaUsa: 'USA Practice & Green Card',
    },
    services: {
      title1: 'International Legal Solutions',
      title2: 'of High Precision',
      desc: 'Private legal practice for high-complexity cases across the US and global financial centers. In-depth analysis of federal legal systems, strategic counsel, and rigorous protection of client interests.',
      btnAll: 'All Practice Areas',
      c1Title: 'USA: Green Card & Citizenship',
      c1Code: '#US IMMIGRATION & GREEN CARD',
      c1Desc: 'Tailored strategy for US permanent residency: EB-1A talent petitions, EB-2 NIW national interest waivers, status adjustments, and citizenship pathways.',
      c2Title: 'International Business & Cross-Border Contracts',
      c2Code: '#INTERNATIONAL BUSINESS',
      c2Desc: 'Corporate structuring across USA (Delaware, Wyoming), UK, EU, and UAE (DIFC / ADGM). Cross-border contracts and institutional compliance.',
      c3Title: 'Private Asset Protection, Funds & Trusts',
      c3Code: '#ASSET PROTECTION & TRUSTS',
      c3Desc: 'Irrevocable international trusts, creditor protection mechanisms, private capital preservation, and cross-border tax shielding.',
      c4Title: 'Cross-Border Disputes & Arbitration',
      c4Code: '#DISPUTES & ARBITRATION',
      c4Desc: 'Strategic advocacy in transnational commercial conflicts, international arbitration, and judgment enforcement across jurisdictions.',
      c5Title: 'Legal Risk Audit & Due Diligence',
      c5Code: '#RISK AUDIT',
      c5Desc: 'Line-by-line legal scrutiny of agreements prior to execution: identifying pitfalls, counterparty vetting, and petition reviews.',
      c6Title: 'Bespoke Transnational Strategy',
      c6Code: '#STRATEGY',
      c6Desc: 'Unified legal roadmap for unprecedented legal scenarios bridging American and international law: Analyze → Strategize → Act.',
    },
    greenCard: {
      badge: 'FLAGSHIP U.S. PRACTICE',
      title1: 'USA: Immigration, Citizenship',
      title2: '& Status Defense',
      desc: '15 years in New York. Bespoke strategy, line-by-line N-400 audit, preparation for 128 Civics Test questions, and mitigation of procedural risks.',
      btnTest: 'Take Immigration Test',
      btnInterview: 'Consular Interview',
      c1Title: 'Green Card & Immigration',
      c1Desc: 'Bespoke pathway to US permanent residency: EB-1A / EB-2 NIW talent petitions, status adjustments, and family petitions.',
      c1Tag: 'Popular',
      c2Title: 'US Citizenship',
      c2Desc: 'Comprehensive legal tracking through the oath ceremony and issuance of the US Passport.',
      c2Tag: 'Flagship',
      c3Title: 'Civics Test 2026',
      c3Desc: 'Preparation for the 2026 128-question test: US history, Constitution, government institutions, and English speech training.',
      c3Tag: '2026 Test',
      c4Title: 'USCIS Interview Preparation',
      c4Desc: 'Mock stress-interview simulations: understanding officer questioning patterns, clear responses, and ambiguity elimination.',
      c4Tag: 'Mock Interview',
      c5Title: 'Form N-400 Audit',
      c5Desc: 'Line-by-line review of your N-400 citizenship filing prior to submission to eradicate hidden procedural hazards.',
      c5Tag: 'Risk Audit',
      c6Title: 'Individual Audit & Strategy',
      c6Desc: 'Personal assessment of citizenship or Green Card eligibility with stress-testing of critical vulnerabilities.',
      c6Tag: 'Bespoke',
      gc1Code: '#GREEN CARD',
      gc2Code: '#US CITIZENSHIP',
      gc3Code: '#CIVICS TEST 2026',
      gc4Code: '#USCIS INTERVIEW',
      gc5Code: '#N-400 AUDIT',
      gc6Code: '#LEGAL STRATEGY',
      stageTitle: '7 Stages of Preparation for US Citizenship',
      s1Title: 'N-400 Analysis',
      s1Desc: 'Line-by-line audit of your form and identification of potential scrutiny areas before submission.',
      s2Title: 'Officer Questioning',
      s2Desc: 'Mastering typical questions and crafting legally accurate answers tailored to your case.',
      s3Title: '2026 Civics Test',
      s3Desc: 'Drilling the 128 civics and history questions (up to 20 asked, 12 required to pass).',
      s4Title: 'English Component',
      s4Desc: 'Reading, writing, and speaking modules with verified phraseology that removes doubt.',
      s5Title: 'N-400 Audit',
      s5Desc: 'Pre-filing detection of red flags in immigration history, travel logs, and tax filings.',
      s6Title: 'Interview Simulation',
      s6Desc: 'Realistic stress-test interview simulation with immediate correction of errors.',
      s7Title: 'Final Readiness',
      s7Desc: 'Complete evidentiary docket, behavioral guidance, and oath ceremony checklist.',
      ctaAudit: 'Start Personal Audit',
      ctaTest: 'Open Interactive Civics Test',
    },
    about: {
      title1: 'International Legal Solutions',
      title2: 'of High Precision',
      desc: 'Private boutique practice for high-complexity legal matters in the United States and global financial capitals. Rigorous analysis of federal legal systems, custom strategy, and surgical defense of client interests.',
      p1Title: '15+ Years Practice in the US',
      p1Desc: 'Deep expertise in US federal law and USCIS regulations. Direct US citizen status, proven track record in complex immigration matters.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Attorney-Client Privilege',
      p2Desc: 'Highest institutional confidentiality standard under Attorney-Client Privilege. Complete legal shield for data, records, and assets.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Jurisdiction Synchronization',
      p3Desc: 'Cross-border structuring across USA (Delaware, Wyoming), EU, UK, and UAE (DIFC). Eliminating tax and procedural collisions.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Analyze → Act Methodology',
      p4Desc: 'Line-by-line pre-filing audit of legal vulnerabilities. Actionable roadmap and targeted execution at every stage.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Explore Practice Principles',
    },
    countries: {
      badge: 'GEOGRAPHY & LEGAL REGIMES',
      title1: 'International Jurisdictions',
      title2: 'of Practice',
      desc: 'Expertise at the crossroads of multiple legal traditions. Harmonizing procedural standards worldwide to secure client objectives.',
      btnAll: 'All Jurisdictions',
      hub1Name: 'United States',
      hub1Badge: 'Primary Focus',
      hub1System: 'US Federal & State Law',
      hub1Desc: 'Immigration pathways (EB-1A / NIW / Citizenship), Delaware & Wyoming corporate law, federal arbitration and status protection.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'UAE (DIFC / ADGM)',
      hub2Badge: 'Global Hub',
      hub2System: 'DIFC Courts & English Common Law',
      hub2Desc: 'International corporate structuring, capital relocation, family offices, and asset protection within Dubai financial jurisdiction.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'United Kingdom',
      hub3Badge: 'Common Law',
      hub3System: 'English Common Law',
      hub3Desc: 'Commercial contracts under English law, London arbitration, prime real estate structuring, and cross-border trusts.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'European Union (EU)',
      hub4Badge: 'European Law',
      hub4System: 'Civil Law & EU Directives',
      hub4Desc: 'Counsel across Germany, France, Cyprus, and Spain. Corporate compliance, regulatory risk mitigation, and international asset protection.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'CORRIDOR:',
    },
    quote: {
      text: '“Law is not just regulations. It is your power to live wherever you choose.”',
      author: 'V. I. Levin',
    },
    footer: {
      manifesto: 'Private international legal counsel for high-stakes challenges. Defending client interests across borders without geographical boundaries.',
      col1: 'Practices',
      s1: 'Immigration & Green Card',
      s2: 'Legal Risk Audit',
      s3: 'Corporate Law',
      s4: 'Cross-Border Contracts',
      s5: 'Family & Inheritance',
      s6: 'Commercial Disputes',
      col2: 'USA & Jurisdictions',
      u1: 'US Green Card (EB-1 / NIW)',
      u2: 'Consular Interview',
      u3: 'Immigration Test',
      u4: 'US Jurisdiction',
      u5: 'Germany & EU',
      u6: 'UAE (Dubai / Abu Dhabi)',
      u7: 'Cyprus (Common Law)',
      col3: 'Practice',
      p1: 'Case Records',
      p2: 'Articles & Legal Analysis',
      p3: 'Confidentiality Manifesto',
      p4: 'Contacts',
      p5: 'Internal Registry',
      disclaimerTitle: 'Legal Disclaimer & Limitation of Liability:',
      disclaimerText: 'Materials published on this website are provided strictly for general informational and analytical purposes and do not constitute formal legal advice or a direct solicitation of legal services in jurisdictions requiring specific state admission. We make no 100% guarantee promises and do not use phrases such as "guaranteed visa or Green Card issuance". Where litigation requires local court admission, licensed co-counsels of the respective Bar Association or Rechtsanwaltskammer are engaged.',
      rights: 'All rights reserved.',
      motto: '“Your rights — without borders.”',
    },
    modal: {
      title: 'Strategic Consultation',
      badge: 'ATTORNEY-CLIENT PRIVILEGE · STRICTLY CONFIDENTIAL',
      catUsa: 'USA & Green Card',
      catBiz: 'Business & Contracts',
      catDisp: 'Disputes & Arbitration',
      catWealth: 'Assets & Trusts',
      catOther: 'Other Inquiries',
      contactLabel: 'Your contact for response *',
      contactPlaceholder: '@username on Telegram or phone / WhatsApp',
      noteLabel: 'Brief overview or query',
      notePlaceholder: 'Describe key circumstances, jurisdictions, or deadlines...',
      submitBtn: 'Submit Request',
      submitting: 'Submitting Request...',
      successTitle: 'Inquiry Received',
      successDesc: 'Legal practice team of V. I. Levin has been notified. We will reach out within 15 minutes.',
      successBtn: 'Close',
      directTg: 'Or message directly via Telegram bot:',
      errorRequired: 'Please provide your Telegram username, phone, or WhatsApp for contact.',
    },
  },

  uk: {
    nav: {
      services: 'Послуги',
      usaGreenCard: 'США & GREEN CARD',
      jurisdictions: 'Юрисдикції',
      about: 'Про практику',
      faq: 'Часті питання',
      contacts: 'Контакти',
      bookConsultation: 'Консультація',
      langTitle: 'Мова / Language',
    },
    headerDropdown: {
      examTitle: 'Підготовка до іспиту на громадянство',
      examDesc: '100 питань з історії та державного устрою США, мовний тренінг',
      examTag: 'Іспит',
      talentTitle: 'Візи талантів (EB-1A / EB-2 NIW)',
      talentDesc: 'Оформлення грін-карти без американського роботодавця для професіоналів',
      talentTag: 'EB-1A',
      interviewTitle: 'Консульське інтерв’ю та безпека',
      interviewDesc: 'Стрес-інтерв’ю, перевірка біографії та алгоритми захисту статусу',
      interviewTag: 'Консул',
      corpTitle: 'Корпоративне та податкове право',
      corpDesc: 'Реєстрація Delaware, Wyoming, структурування володіння',
      corpTag: 'Бізнес',
    },
    hero: {
      badge: 'МІЖНАРОДНА ЮРИДИЧНА ДОПОМОГА',
      title1: 'Ваші права —',
      title2: 'без кордонів',
      desc: 'Професійна юридична підтримка для людей та бізнесу в США і по всьому світу.',
      flow1: 'Складна справа',
      flow2: 'Глибокий аналіз',
      flow3: 'Стратегія',
      flow4: 'Рішення',
      badgeNy: '15 років у Нью-Йорку',
      badgeCitizen: 'Громадянин США',
      ctaConsultation: 'Стратегічна консультація',
      ctaUsa: 'Практика США & Green Card',
    },
    services: {
      title1: 'Міжнародні юридичні рішення',
      title2: 'високої точності',
      desc: 'Приватна юридична практика для кейсів підвищеної складності в США та глобальних фінансових центрах. Глибокий аналіз федеральної правової системи, нестандартна стратегія та захист інтересів довірителя.',
      btnAll: 'Всі напрямки практики',
      c1Title: 'США: Green Card & Громадянство',
      c1Code: '#ІММІГРАЦІЯ & GREEN CARD',
      c1Desc: 'Індивідуальна стратегія набуття статусу резидента США: візи талантів EB-1A, національні інтереси EB-2 NIW, зміна статусу та супровід до отримання громадянства США.',
      c2Title: 'Міжнародний бізнес та транскордонні контракти',
      c2Code: '#МІЖНАРОДНИЙ БІЗНЕС',
      c2Desc: 'Корпоративне структурування в США (Delaware, Wyoming), Великій Британії, ЄС та ОАЕ (DIFC / ADGM). Міжнародні контракти та комплаєнс.',
      c3Title: 'Захист приватних активів, фонди та трасти',
      c3Code: '#ЗАХИСТ АКТИВІВ & ТРАСТИ',
      c3Desc: 'Створення безвідкличних міжнародних трастів, захист капіталу від зазіхань, безпечне володіння активами та податковий захист.',
      c4Title: 'Транскордонні судові спори та арбітраж',
      c4Code: '#АРБІТРАЖ ТА СУДИ',
      c4Desc: 'Захист інтересів приватних осіб та компаній у міжнародних комерційних конфліктах, арбітраж та визнання судових рішень.',
      c5Title: 'Аудит юридичних ризиків та Due Diligence',
      c5Code: '#АУДИТ РИЗИКІВ',
      c5Desc: 'Порядковий юридичний аудит документів до їх підписання: виявлення пасток, перевірка контрагентів, аудит імміграційних справ.',
      c6Title: 'Індивідуальна транскордонна стратегія',
      c6Code: '#СТРАТЕГІЯ',
      c6Desc: 'Комплексний юридичний маршрут для нестандартних ситуацій на стику американського та міжнародного права: Analyze → Strategize → Act.',
    },
    greenCard: {
      badge: 'ФЛАГМАНСЬКА АМЕРИКАНСЬКА ПРАКТИКА',
      title1: 'США: Імміграція, Громадянство',
      title2: 'та Захист статусу',
      desc: '15 років у Нью-Йорку. Персональна стратегія, порядковий аудит заяви N-400, опрацювання 128 питань Civics Test та усунення процесуальних ризиків.',
      btnTest: 'Пройти тест на імміграцію',
      btnInterview: 'Консульське інтерв’ю',
      c1Title: 'Green Card & Імміграція',
      c1Desc: 'Індивідуальна стратегія набуття статусу резидента: візи талантів EB-1A / EB-2 NIW, зміна статусу та сімейні петиції.',
      c1Tag: 'Популярне',
      c2Title: 'Громадянство США',
      c2Desc: 'Комплексний юридичний супровід заявника до прийняття присяги та отримання американського паспорта.',
      c2Tag: 'Флагман',
      c3Title: 'Civics Test 2026',
      c3Desc: 'Підготовка до актуального тесту 2026 року на 128 питань: історія США, Конституція, органи влади та мовний мінімум.',
      c3Tag: '2026 Test',
      c4Title: 'Підготовка до інтерв’ю USCIS',
      c4Desc: 'Репетиція стрес-співбесід з американським офіцером: що запитують, як відповідати та як прибрати двозначності.',
      c4Tag: 'Mock Interview',
      c5Title: 'Аудит заяви N-400',
      c5Desc: 'Порядковий юридичний розбір анкети N-400 на громадянство США до її подання для виключення прихованих пасток.',
      c5Tag: 'Аудит ризиків',
      c6Title: 'Індивідуальний аудит та стратегія',
      c6Desc: 'Персональна оцінка шансів на громадянство або Green Card з моделюванням критичних зон вашої справи.',
      c6Tag: 'Bespoke',
      gc1Code: '#GREEN CARD',
      gc2Code: '#ГРОМАДЯНСТВО США',
      gc3Code: '#CIVICS TEST 2026',
      gc4Code: "#ІНТЕРВ'Ю USCIS",
      gc5Code: '#АУДИТ N-400',
      gc6Code: '#ПРАВОВА СТРАТЕГІЯ',
      stageTitle: '7 етапів підготовки до отримання громадянства США',
      s1Title: 'Аналіз N-400',
      s1Desc: 'Порядковий розбір анкети та виявлення потенційно проблемних місць до відправлення.',
      s2Title: 'Питання офіцера',
      s2Desc: 'Що запитує офіцер, як коректно формулювати відповіді щодо вашої ситуації.',
      s3Title: '2026 Civics Test',
      s3Desc: 'Відпрацювання 128 питань з історії та устрою США (до 20 ставлять, 12 для зарахування).',
      s4Title: 'English Component',
      s4Desc: 'Читання, письмо та розмовний блок: формулювання, що знімають сумніви офіцера.',
      s5Title: 'N-400 Audit',
      s5Desc: 'Виявлення «червоних прапорців» у біографії, поїздках і податках до подання.',
      s6Title: 'Симуляція інтерв’ю',
      s6Desc: 'Моделювання реальної співбесіди у форматі стрес-тесту з розбором помилок.',
      s7Title: 'Фінальна готовність',
      s7Desc: 'Пакет документів, стратегія поведінки та чек-лист для дня присяги.',
      ctaAudit: 'Розпочати персональний аудит',
      ctaTest: 'Відкрити інтерактивний Civics Test',
    },
    about: {
      title1: 'Міжнародні юридичні рішення',
      title2: 'високої точності',
      desc: 'Приватна практика для кейсів підвищеної складності в США та ключових фінансових центрах світу. Глибокий аналіз федерального права, нестандартна стратегія та покроковий захист інтересів клієнта.',
      p1Title: '15+ років практики в США',
      p1Desc: 'Глибока експертиза у федеральному праві та USCIS. Особистий статус громадянина США, досвід ведення складних імміграційних кейсів.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Сувора конфіденційність',
      p2Desc: 'Інституційна конфіденційність найвищого рівня за стандартом Attorney-Client Privilege. Повний захист персональних даних та активів.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Синхронізація юрисдикцій',
      p3Desc: 'Транскордонне структурування: США (Delaware, Wyoming), ЄС, Велика Британія та ОАЕ (DIFC). Усунення правових конфліктів.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Методологія Analyze → Act',
      p4Desc: 'Порядковий аудит юридичних ризиків до подання будь-яких форм. Вивірена дорожня карта захисту інтересів клієнта.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Детальніше про принципи практики',
    },
    countries: {
      badge: 'ГЕОГРАФІЯ ТА ПРАВОВІ СИСТЕМИ',
      title1: 'Міжнародні юрисдикції',
      title2: 'практики',
      desc: 'Компетенції на стику різних правових систем. Ми гармонізуємо процесуальні норми для захисту ваших інтересів.',
      btnAll: 'Всі юрисдикції',
      hub1Name: 'США',
      hub1Badge: 'Ключовий фокус',
      hub1System: 'Федеральне право США & Право штатів',
      hub1Desc: 'Імміграційний трекінг (EB-1A / NIW / Громадянство), корпоративне право Delaware і Wyoming, федеральний арбітраж.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'ОАЕ (DIFC / ADGM)',
      hub2Badge: 'Транскордонний хаб',
      hub2System: 'DIFC Courts & English Common Law',
      hub2Desc: 'Структурування міжнародних компаній, релокація капіталу, сімейні офіси та захист активів у фінансовому центрі Дубая.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'Велика Британія',
      hub3Badge: 'Англійське право',
      hub3System: 'English Common Law',
      hub3Desc: 'Комерційні контракти за англійським правом, лондонський арбітраж, структурування нерухомості та трасти.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'Європейський Союз (ЄС)',
      hub4Badge: 'Європейське право',
      hub4System: 'Civil Law & Регламенти ЄС',
      hub4Desc: 'Юридичний супровід у Німеччині, Франції, на Кіпрі та в Іспанії. Корпоративний комплаєнс та захист активів.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'КОРИДОР:',
    },
    quote: {
      text: '«Право — це не лише закони. Це можливість жити там, де ви хочете.»',
      author: 'V. I. Levin',
    },
    footer: {
      manifesto: 'Міжнародна юридична практика для складних завдань. Захист інтересів приватних клієнтів та бізнесу без кордонів і географічних бар’єрів.',
      col1: 'Напрямки',
      s1: 'Імміграція та Green Card',
      s2: 'Правовий аудит',
      s3: 'Корпоративне право',
      s4: 'Міжнародні контракти',
      s5: 'Сімейне та спадкове',
      s6: 'Судові спори',
      col2: 'США та Країни',
      u1: 'Green Card США (EB-1 / NIW)',
      u2: 'Консульське інтерв’ю',
      u3: 'Тест на імміграцію',
      u4: 'Юрисдикція США',
      u5: 'Німеччина та ЄС',
      u6: 'ОАЕ (Дубай / Абу-Дабі)',
      u7: 'Кіпр (Common Law)',
      col3: 'Практика',
      p1: 'Анонімізовані кейси',
      p2: 'Статті та правовий аналіз',
      p3: 'Маніфест конфіденційності',
      p4: 'Контакти',
      p5: 'Внутрішній реєстр',
      disclaimerTitle: 'Юридичний дисклеймер та обмеження відповідальності:',
      disclaimerText: 'Матеріали, опубліковані на цьому сайті, мають виключно інформаційно-аналітичний характер і не є індивідуальною юридичною консультацією. Ми не даємо обіцянок 100% гарантії позитивного результату справ. У випадках, що вимагають судового представництва, залучаються локальні ліцензовані адвокати відповідної асоціації (Bar Association / Rechtsanwaltskammer).',
      rights: 'Всі права захищені.',
      motto: '«Ваші права — без кордонів.»',
    },
    modal: {
      title: 'Стратегічна консультація',
      badge: 'ATTORNEY-CLIENT PRIVILEGE · СТРОГО КОНФІДЕНЦІЙНО',
      catUsa: 'США & Green Card',
      catBiz: 'Бізнес & Контракти',
      catDisp: 'Спори & Арбітраж',
      catWealth: 'Активи & Трасти',
      catOther: 'Інші питання',
      contactLabel: 'Ваш контакт для зв’язку *',
      contactPlaceholder: '@username в Telegram або телефон / WhatsApp',
      noteLabel: 'Суть питання або коментар',
      notePlaceholder: 'Опишіть ключові обставини, юрисдикції або дедлайни...',
      submitBtn: 'Надіслати запит',
      submitting: 'Надсилання запиту...',
      successTitle: 'Запит прийнято',
      successDesc: 'Правовий департамент V. I. Levin та черговий спеціаліст повідомлені. Ми зв’яжемося з вами протягом 15 хвилин.',
      successBtn: 'Закрити',
      directTg: 'Або напишіть напряму в Telegram-бот:',
      errorRequired: 'Будь ласка, вкажіть ваш Telegram, телефон або WhatsApp для зв’язку.',
    },
  },

  es: {
    nav: {
      services: 'Servicios',
      usaGreenCard: 'EE.UU. & GREEN CARD',
      jurisdictions: 'Jurisdicciones',
      about: 'Sobre el bufete',
      faq: 'Preguntas',
      contacts: 'Contactos',
      bookConsultation: 'Consulta',
      langTitle: 'Idioma / Language',
    },
    headerDropdown: {
      examTitle: 'Preparación para el examen de ciudadanía',
      examDesc: '100 preguntas de historia y educación cívica de EE. UU., preparación lingüística',
      examTag: 'Examen',
      talentTitle: 'Visas de talento (EB-1A / EB-2 NIW)',
      talentDesc: 'Green Card sin patrocinio de empleador para profesionales',
      talentTag: 'EB-1A',
      interviewTitle: 'Entrevista consular y seguridad',
      interviewDesc: 'Verificación de antecedentes y simulaciones de entrevista de seguridad',
      interviewTag: 'Cónsul',
      corpTitle: 'Derecho corporativo y fiscal',
      corpDesc: 'Registro en Delaware, Wyoming, estructuración de activos',
      corpTag: 'Negocios',
    },
    hero: {
      badge: 'ASISTENCIA LEGAL INTERNACIONAL',
      title1: 'Sus derechos —',
      title2: 'sin fronteras',
      desc: 'Asesoramiento legal profesional y defensa institucional para particulares y empresas en EE.UU. y en todo el mundo.',
      flow1: 'Caso complejo',
      flow2: 'Análisis preciso',
      flow3: 'Estrategia',
      flow4: 'Solución protegida',
      badgeNy: '15 años en Nueva York',
      badgeCitizen: 'Ciudadano de EE.UU.',
      ctaConsultation: 'Consulta estratégica',
      ctaUsa: 'Práctica EE.UU. & Green Card',
    },
    services: {
      title1: 'Soluciones jurídicas integrales',
      title2: 'sin plantillas',
      desc: 'V. I. LEVIN — bufete privado para particulares y empresas que requieren resolver situaciones complejas en EE. UU. o múltiples jurisdicciones.',
      btnAll: 'Todas las áreas de práctica',
      c1Title: 'EE.UU.: Green Card & Ciudadanía',
      c1Code: '#INMIGRACIÓN Y GREEN CARD',
      c1Desc: 'Estrategia a medida para residencia permanente en EE. UU.: peticiones de talento EB-1A, exención por interés nacional EB-2 NIW y ciudadanía estadounidense.',
      c2Title: 'Negocios internacionales y contratos transfronterizos',
      c2Code: '#NEGOCIOS INTERNACIONALES',
      c2Desc: 'Estructuración societaria en EE. UU. (Delaware, Wyoming), Reino Unido, UE y EAU (DIFC / ADGM). Contratos transfronterizos y cumplimiento normativo.',
      c3Title: 'Protección de patrimonio privado, fondos y fideicomisos',
      c3Code: '#PROTECCIÓN DE ACTIVOS Y TRUSTS',
      c3Desc: 'Constitución de fideicomisos irrevocables internacionales, blindaje de capitales frente a contingencias y optimización fiscal transfronteriza.',
      c4Title: 'Litigios transfronterizos y arbitraje comercial',
      c4Code: '#ARBITRAJE Y LITIGIOS',
      c4Desc: 'Defensa estratégica en disputas comerciales internacionales, arbitraje internacional y ejecución transnacional de resoluciones judiciales.',
      c5Title: 'Auditoría preventiva de riesgos y Due Diligence',
      c5Code: '#AUDITORÍA DE RIESGOS',
      c5Desc: 'Auditoría jurídica exhaustiva línea por línea antes de firmar: identificación de cláusulas trampa, verificación de contrapartes y auditoría de peticiones.',
      c6Title: 'Estrategia jurídica transfronteriza personalizada',
      c6Code: '#ESTRATEGIA',
      c6Desc: 'Itinerario legal integral para casos atípicos en la confluencia del derecho estadounidense e internacional: Analyze → Strategize → Act.',
    },
    greenCard: {
      badge: 'PRÁCTICA ESTADOUNIDENSE DE REFERENCIA',
      title1: 'EE. UU.: Inmigración, Ciudadanía',
      title2: 'y Protección de estatus',
      desc: '15 años en Nueva York. Estrategia personalizada, auditoría línea por línea del formulario N-400, preparación para las 128 preguntas del Civics Test.',
      btnTest: 'Test de Inmigración',
      btnInterview: 'Entrevista Consular',
      c1Title: 'Green Card & Inmigración',
      c1Desc: 'Estrategia personalizada para estatus de residente permanente: visas de talento EB-1A / EB-2 NIW, ajuste de estatus y peticiones familiares.',
      c1Tag: 'Popular',
      c2Title: 'Ciudadanía de EE. UU.',
      c2Desc: 'Seguimiento legal completo del solicitante hasta la ceremonia de juramento y expedición del pasaporte estadounidense.',
      c2Tag: 'Flagship',
      c3Title: 'Civics Test 2026',
      c3Desc: 'Preparación para el examen de 128 preguntas: historia de EE. UU., Constitución, instituciones y entrenamiento en inglés.',
      c3Tag: 'Test 2026',
      c4Title: 'Preparación para entrevista USCIS',
      c4Desc: 'Simulacros de entrevistas bajo presión con oficial de inmigración: patrones de interrogatorio y eliminación de ambigüedades.',
      c4Tag: 'Mock Interview',
      c5Title: 'Auditoría del formulario N-400',
      c5Desc: 'Revisión jurídica exhaustiva del formulario N-400 de ciudadanía antes de su entrega para neutralizar riesgos procesales.',
      c5Tag: 'Auditoría',
      c6Title: 'Auditoría individual y estrategia',
      c6Desc: 'Evaluación personalizada de opciones de ciudadanía o Green Card con análisis de puntos críticos de su expediente.',
      c6Tag: 'Bespoke',
      stageTitle: '7 etapas de preparación para la ciudadanía estadounidense',
      s1Title: 'Análisis N-400',
      s1Desc: 'Revisión exhaustiva del formulario y detección de puntos vulnerables antes del envío.',
      s2Title: 'Preguntas del oficial',
      s2Desc: 'Respuestas precisas y técnicamente correctas formuladas conforme a su caso específico.',
      s3Title: 'Civics Test 2026',
      s3Desc: 'Dominio de las 128 preguntas oficiales de historia y educación cívica.',
      s4Title: 'Componente de inglés',
      s4Desc: 'Módulos de lectura, escritura y conversación con lenguaje riguroso que despeja dudas.',
      s5Title: 'Auditoría N-400',
      s5Desc: 'Identificación de alertas en historial migratorio, viajes e impuestos.',
      s6Title: 'Simulación de entrevista',
      s6Desc: 'Ensayo real en formato de estrés con análisis correctivo inmediato.',
      s7Title: 'Preparación final',
      s7Desc: 'Expediente probatorio completo, protocolo de conducta y guía para el día del juramento.',
      ctaAudit: 'Iniciar auditoría personal',
      ctaTest: 'Abrir Civics Test interactivo',
    },
    about: {
      title1: 'Soluciones legales internacionales',
      title2: 'de alta precisión',
      desc: 'Práctica privada para casos de alta complejidad en EE.UU. y principales centros financieros mundiales. Análisis exhaustivo del derecho federal y defensa rigurosa de los intereses del cliente.',
      p1Title: '15+ años de práctica en EE.UU.',
      p1Desc: 'Profundo conocimiento del derecho federal y normativa USCIS. Condición directa de ciudadano estadounidense con amplia trayectoria en inmigración.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Secreto profesional absoluto',
      p2Desc: 'Confidencialidad institucional bajo el estándar Attorney-Client Privilege. Protección legal completa de datos, documentos y patrimonio.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Sincronización de jurisdicciones',
      p3Desc: 'Estructuración transfronteriza: EE.UU. (Delaware, Wyoming), UE, Reino Unido y EAU (DIFC). Prevención de colisiones fiscales y procesales.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Metodología Analyze → Act',
      p4Desc: 'Auditoría preventiva línea por línea antes de presentar cualquier formulario oficial. Plan de acción preciso y eficaz.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Conozca los principios del bufete',
    },
    countries: {
      badge: 'GEOGRAFÍA Y SISTEMAS LEGALES',
      title1: 'Jurisdicciones internacionales',
      title2: 'de práctica',
      desc: 'Competencia en la intersección de múltiples sistemas jurídicos. Armonizamos normativas internacionales para proteger sus intereses.',
      btnAll: 'Todas las jurisdicciones',
      hub1Name: 'Estados Unidos',
      hub1Badge: 'Foco principal',
      hub1System: 'Derecho Federal y Estatal de EE.UU.',
      hub1Desc: 'Vías migratorias (EB-1A / NIW / Ciudadanía), derecho societario en Delaware y Wyoming, arbitraje federal y protección de estatus.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'EAU (DIFC / ADGM)',
      hub2Badge: 'Hub global',
      hub2System: 'Tribunales DIFC & Common Law',
      hub2Desc: 'Estructuración corporativa internacional, relocalización de capital, oficinas familiares y protección de activos en Dubái.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'Reino Unido',
      hub3Badge: 'Common Law',
      hub3System: 'English Common Law',
      hub3Desc: 'Contratos comerciales según derecho inglés, arbitraje en Londres, estructuración inmobiliaria y fideicomisos.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'Unión Europea (UE)',
      hub4Badge: 'Derecho europeo',
      hub4System: 'Civil Law & Directivas de la UE',
      hub4Desc: 'Asesoramiento en Alemania, Francia, Chipre y España. Cumplimiento normativo corporativo y protección patrimonial.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'CORREDOR:',
    },
    quote: {
      text: '«El derecho no son solo leyes. Es el poder de vivir donde usted elija.»',
      author: 'V. I. Levin',
    },
    footer: {
      manifesto: 'Práctica jurídica internacional para asuntos de máxima complejidad. Defensa institucional de intereses privados y corporativos sin fronteras.',
      col1: 'Áreas de práctica',
      s1: 'Inmigración y Green Card',
      s2: 'Auditoría jurídica',
      s3: 'Derecho societario',
      s4: 'Contratos internacionales',
      s5: 'Familia y sucesiones',
      s6: 'Litigios y arbitraje',
      col2: 'EE.UU. y Jurisdicciones',
      u1: 'Green Card EE.UU. (EB-1 / NIW)',
      u2: 'Entrevista consular',
      u3: 'Test de inmigración',
      u4: 'Jurisdicción EE.UU.',
      u5: 'Alemania y UE',
      u6: 'EAU (Dubái / Abu Dabi)',
      u7: 'Chipre (Common Law)',
      col3: 'Bufete',
      p1: 'Casos y precedentes',
      p2: 'Artículos y doctrina',
      p3: 'Manifiesto de confidencialidad',
      p4: 'Contacto',
      p5: 'Registro interno',
      disclaimerTitle: 'Aviso legal y limitación de responsabilidad:',
      disclaimerText: 'Los contenidos de este sitio tienen carácter estrictamente informativo y analítico, no constituyendo asesoramiento jurídico individualizado. No garantizamos resultados al 100%. Cuando se requiere representación procesal ante tribunales nacionales, se actúa en colaboración con abogados locales colegiados.',
      rights: 'Todos los derechos reservados.',
      motto: '«Sus derechos — sin fronteras.»',
    },
    modal: {
      title: 'Consulta Estratégica',
      badge: 'ATTORNEY-CLIENT PRIVILEGE · ESTRICTAMENTE CONFIDENCIAL',
      catUsa: 'EE.UU. & Green Card',
      catBiz: 'Negocios & Contratos',
      catDisp: 'Disputas & Arbitraje',
      catWealth: 'Activos & Fideicomisos',
      catOther: 'Otras consultas',
      contactLabel: 'Su contacto de comunicación *',
      contactPlaceholder: '@usuario de Telegram o teléfono / WhatsApp',
      noteLabel: 'Resumen del asunto',
      notePlaceholder: 'Indique circunstancias esenciales, jurisdicciones o plazos...',
      submitBtn: 'Enviar solicitud',
      submitting: 'Enviando solicitud...',
      successTitle: 'Solicitud Recibida',
      successDesc: 'El equipo legal de V. I. Levin ha sido notificado. Nos comunicaremos en 15 minutos.',
      successBtn: 'Cerrar',
      directTg: 'O comuníquese directamente mediante bot de Telegram:',
      errorRequired: 'Por favor, indique su Telegram, teléfono o WhatsApp de contacto.',
    },
  },

  it: {
    nav: {
      services: 'Servizi',
      usaGreenCard: 'USA & GREEN CARD',
      jurisdictions: 'Giurisdizioni',
      about: 'Chi siamo',
      faq: 'FAQ',
      contacts: 'Contatti',
      bookConsultation: 'Consulenza',
      langTitle: 'Lingua / Language',
    },
    headerDropdown: {
      examTitle: 'Preparazione all’esame di cittadinanza',
      examDesc: '100 domande di storia e civica USA, training linguistico',
      examTag: 'Esame',
      talentTitle: 'Visti per talenti (EB-1A / EB-2 NIW)',
      talentDesc: 'Green Card senza sponsorizzazione del datore di lavoro per professionisti',
      talentTag: 'EB-1A',
      interviewTitle: 'Colloquio consolare e sicurezza',
      interviewDesc: 'Controllo dei precedenti e simulazioni del colloquio consolare',
      interviewTag: 'Console',
      corpTitle: 'Diritto societario e fiscale',
      corpDesc: 'Registrazione Delaware, Wyoming, strutturazione degli asset',
      corpTag: 'Impresa',
    },
    hero: {
      badge: 'ASSISTENZA LEGALE INTERNAZIONALE',
      title1: 'I vostri diritti —',
      title2: 'senza frontiere',
      desc: 'Patrocinio legale professionale e tutela istituzionale per privati e imprese negli Stati Uniti e nel mondo.',
      flow1: 'Caso complesso',
      flow2: 'Analisi rigorosa',
      flow3: 'Strategia',
      flow4: 'Soluzione solida',
      badgeNy: '15 anni a New York',
      badgeCitizen: 'Cittadino USA',
      ctaConsultation: 'Consulenza strategica',
      ctaUsa: 'Pratica USA & Green Card',
    },
    services: {
      title1: 'Soluzioni legali integrate',
      title2: 'senza compromessi',
      desc: 'V. I. LEVIN — studio legale privato per privati e imprese che affrontano questioni complesse negli Stati Uniti e in contesti transfrontalieri.',
      btnAll: 'Tutte le aree di pratica',
      c1Title: 'USA: Green Card & Cittadinanza',
      c1Code: '#IMMIGRAZIONE & GREEN CARD',
      c1Desc: 'Strategia personalizzata per residenza permanente USA: petizioni EB-1A per talenti straordinari, EB-2 NIW e cittadinanza americana.',
      c2Title: 'Affari internazionali e contratti transfrontalieri',
      c2Code: '#BUSINESS INTERNAZIONALE',
      c2Desc: 'Strutturazione societaria in USA (Delaware, Wyoming), Regno Unito, UE e EAU (DIFC / ADGM). Contratti e compliance internazionale.',
      c3Title: 'Protezione patrimoni privati, fondi e trust',
      c3Code: '#PROTEZIONE PATRIMONIO & TRUST',
      c3Desc: 'Costituzione di trust internazionali irrevocabili, schermatura da creditori e ottimizzazione fiscale transfrontaliera.',
      c4Title: 'Contenzioso transfrontaliero e arbitrato',
      c4Code: '#ARBITRATO & CONTENZIOSO',
      c4Desc: 'Tutela strategica in controversie commerciali transnazionali, arbitrato internazionale e riconoscimento decisioni estere.',
      c5Title: 'Audit dei rischi legali e Due Diligence',
      c5Code: '#AUDIT DEI RISCHI',
      c5Desc: 'Verifica analitica riga per riga dei contratti prima della stipula: individuazione clausole critiche e controllo controparti.',
      c6Title: 'Strategia transfrontaliera su misura',
      c6Code: '#STRATEGIA',
      c6Desc: 'Itinerario legale coordinato per fattispecie complesse tra ordinamento statunitense e diritto internazionale: Analyze → Strategize → Act.',
    },
    greenCard: {
      badge: 'PRATICA STATUNITENSE DI PUNTA',
      title1: 'USA: Immigrazione, Cittadinanza',
      title2: 'e Difesa dello status',
      desc: '15 anni a New York. Strategia personalizzata, audit riga per riga del Modulo N-400, preparazione alle 128 domande del Civics Test.',
      btnTest: 'Test di immigrazione',
      btnInterview: 'Colloquio consolare',
      c1Title: 'Green Card & Immigrazione',
      c1Desc: 'Percorso personalizzato per il soggiorno permanente: visti talento EB-1A / EB-2 NIW, adeguamento status e ricongiungimenti.',
      c1Tag: 'Richiesto',
      c2Title: 'Cittadinanza USA',
      c2Desc: 'Affiancamento giuridico costante fino al giuramento e al rilascio del Passaporto statunitense.',
      c2Tag: 'Flagship',
      c3Title: 'Civics Test 2026',
      c3Desc: 'Preparazione all’esame di 128 domande su storia, Costituzione e istituzioni americane con training linguistico in inglese.',
      c3Tag: 'Test 2026',
      c4Title: 'Preparazione colloquio USCIS',
      c4Desc: 'Simulazione di colloqui sotto stress con ufficiale d’immigrazione: formulazione corretta e rimozione ambiguità.',
      c4Tag: 'Mock Interview',
      c5Title: 'Audit del Modulo N-400',
      c5Desc: 'Analisi legale riga per riga dell’istanza prima dell’invio per scongiurare criticità procedurali.',
      c5Tag: 'Audit rischi',
      c6Title: 'Audit e strategia individuale',
      c6Desc: 'Valutazione delle probabilità di successo per cittadinanza o Green Card con verifica delle aree vulnerabili.',
      c6Tag: 'Bespoke',
      gc1Code: '#GREEN CARD',
      gc2Code: '#CITTADINANZA USA',
      gc3Code: '#CIVICS TEST 2026',
      gc4Code: '#COLLOQUIO USCIS',
      gc5Code: '#AUDIT N-400',
      gc6Code: '#STRATEGIA LEGALE',
      stageTitle: '7 fasi di preparazione per la cittadinanza statunitense',
      s1Title: 'Analisi N-400',
      s1Desc: 'Esame puntuale della domanda e identificazione di possibili criticità prima della trasmissione.',
      s2Title: 'Domande dell’ufficiale',
      s2Desc: 'Gestione delle domande tipiche e formulazione di risposte giuridicamente ineccepibili.',
      s3Title: 'Civics Test 2026',
      s3Desc: 'Studio approfondito delle 128 domande ufficiali di educazione civica e storia USA.',
      s4Title: 'Componente inglese',
      s4Desc: 'Lettura, scrittura e colloquio orale con lessico idoneo a superare ogni perplessità.',
      s5Title: 'Audit N-400',
      s5Desc: 'Prevenzione di discordanze su viaggi pregressi, regolarità fiscale e status storico.',
      s6Title: 'Simulazione intervista',
      s6Desc: 'Sessione di simulazione ad alta intensità con correzione puntuale degli errori.',
      s7Title: 'Convalida finale',
      s7Desc: 'Fascicolo probatorio definitivo, guida comportamentale e checklist per il giuramento.',
      ctaAudit: 'Avvia audit personale',
      ctaTest: 'Apri Civics Test interattivo',
    },
    about: {
      title1: 'Soluzioni legali internazionali',
      title2: 'ad alta precisione',
      desc: 'Boutique legale privata per casi di elevata complessità negli Stati Uniti e nei poli finanziari globali. Analisi rigorosa del diritto federale e difesa intransigente degli interessi del cliente.',
      p1Title: '15+ anni di pratica negli USA',
      p1Desc: 'Profonda competenza in diritto federale e prassi USCIS. Status diretto di cittadino statunitense ed esperienza in pratiche complesse.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Segreto professionale istituzionale',
      p2Desc: 'Riservatezza assoluta garantita dallo standard Attorney-Client Privilege. Schermatura totale di dati, atti e asset.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Sincronizzazione delle giurisdizioni',
      p3Desc: 'Strutturazione transfrontaliera: USA (Delaware, Wyoming), UE, Regno Unito ed EAU (DIFC). Prevenzione di conflitti normativi.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Metodologia Analyze → Act',
      p4Desc: 'Audit preventivo riga per riga prima della trasmissione di qualsiasi atto. Tabella di marcia calibrata e risolutiva.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Scopri i principi dello studio',
    },
    countries: {
      badge: 'GEOGRAFIA E ORDINAMENTI GIURIDICI',
      title1: 'Giurisdizioni internazionali',
      title2: 'di competenza',
      desc: 'Competenze all’intersezione di diversi ordinamenti. Armonizziamo le procedure internazionali a tutela dei vostri interessi.',
      btnAll: 'Tutte le giurisdizioni',
      hub1Name: 'Stati Uniti',
      hub1Badge: 'Focus principale',
      hub1System: 'Diritto Federale e Statale USA',
      hub1Desc: 'Immigrazione (EB-1A / NIW / Cittadinanza), diritto societario in Delaware e Wyoming, contenzioso federale e status.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'EAU (DIFC / ADGM)',
      hub2Badge: 'Hub globale',
      hub2System: 'Corti DIFC & Common Law',
      hub2Desc: 'Strutturazione societaria internazionale, allocazione patrimoniale, family office e tutela dei beni a Dubai.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'Regno Unito',
      hub3Badge: 'Common Law',
      hub3System: 'English Common Law',
      hub3Desc: 'Contratti commerciali di diritto inglese, arbitrato a Londra, strutturazione immobiliare e trust transfrontalieri.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'Unione Europea (UE)',
      hub4Badge: 'Diritto europeo',
      hub4System: 'Civil Law & Direttive UE',
      hub4Desc: 'Assistenza in Germania, Francia, Cipro e Spagna. Compliance societaria e gestione patrimoniale transfrontaliera.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'CORRIDOIO:',
    },
    quote: {
      text: '«Il diritto non è solo leggi. È il potere di vivere ovunque desideriate.»',
      author: 'V. I. Levin',
    },
    footer: {
      manifesto: 'Studio legale internazionale per sfide complesse. Tutela dei clienti privati e delle imprese senza confini territoriali.',
      col1: 'Aree di attività',
      s1: 'Immigrazione e Green Card',
      s2: 'Audit legale dei rischi',
      s3: 'Diritto societario',
      s4: 'Contratti internazionali',
      s5: 'Famiglia e successioni',
      s6: 'Contenzioso e arbitrato',
      col2: 'USA e Giurisdizioni',
      u1: 'Green Card USA (EB-1 / NIW)',
      u2: 'Colloquio consolare',
      u3: 'Test di immigrazione',
      u4: 'Giurisdizione USA',
      u5: 'Germania e UE',
      u6: 'EAU (Dubai / Abu Dhabi)',
      u7: 'Cipro (Common Law)',
      col3: 'Studio',
      p1: 'Casi e precedenti',
      p2: 'Articoli e approfondimenti',
      p3: 'Manifesto di riservatezza',
      p4: 'Contatti',
      p5: 'Registro interno',
      disclaimerTitle: 'Disclaimer legale e limitazione di responsabilità:',
      disclaimerText: 'I contenuti del presente sito hanno finalità puramente informative e non costituiscono consulenza legale vincolante né sollecitazione di clientela. Non si rilasciano garanzie al 100% sull’esito dei procedimenti. Nei casi che richiedono difesa giudiziale dinanzi alle corti territoriali, collaboriamo con avvocati abilitati localmente.',
      rights: 'Tutti i diritti riservati.',
      motto: '«I vostri diritti — senza frontiere.»',
    },
    modal: {
      title: 'Consulenza Strategica',
      badge: 'ATTORNEY-CLIENT PRIVILEGE · STRETTAMENTE RISERVATO',
      catUsa: 'USA & Green Card',
      catBiz: 'Impresa & Contratti',
      catDisp: 'Contenzioso & Arbitrato',
      catWealth: 'Patrimonio & Trust',
      catOther: 'Altre questioni',
      contactLabel: 'Recapito per la risposta *',
      contactPlaceholder: '@username Telegram o telefono / WhatsApp',
      noteLabel: 'Sintesi del quesito',
      notePlaceholder: 'Indichi elementi chiave, giurisdizioni o scadenze...',
      submitBtn: 'Invia richiesta',
      submitting: 'Invio in corso...',
      successTitle: 'Richiesta Ricevuta',
      successDesc: 'Il team legale di V. I. Levin è stato informato. La ricontatteremo entro 15 minuti.',
      successBtn: 'Chiudi',
      directTg: 'Oppure scriva direttamente via bot Telegram:',
      errorRequired: 'Si prega di indicare il proprio contatto Telegram, telefono o WhatsApp.',
    },
  },

  fr: {
    nav: {
      services: 'Services',
      usaGreenCard: 'USA & GREEN CARD',
      jurisdictions: 'Juridictions',
      about: 'À propos',
      faq: 'FAQ',
      contacts: 'Contacts',
      bookConsultation: 'Consultation',
      langTitle: 'Langue / Language',
    },
    headerDropdown: {
      examTitle: 'Préparation à l’examen de citoyenneté',
      examDesc: '100 questions d’histoire et d’instruction civique des États-Unis, formation linguistique',
      examTag: 'Examen',
      talentTitle: 'Visas pour talents (EB-1A / EB-2 NIW)',
      talentDesc: 'Green Card sans parrainage d’employeur pour les professionnels',
      talentTag: 'EB-1A',
      interviewTitle: 'Entretien consulaire et sécurité',
      interviewDesc: 'Contrôles des antécédents et simulations d’entretien consulaire',
      interviewTag: 'Consul',
      corpTitle: 'Droit des affaires et fiscalité',
      corpDesc: 'Immatriculation Delaware, Wyoming, structuration d’actifs',
      corpTag: 'Entreprise',
    },
    hero: {
      badge: 'ASSISTANCE JURIDIQUE INTERNATIONALE',
      title1: 'Vos droits —',
      title2: 'sans frontières',
      desc: 'Conseil juridique de haut niveau et défense institutionnelle pour les particuliers et les entreprises aux États-Unis et dans le monde.',
      flow1: 'Dossier complexe',
      flow2: 'Analyse chirurgicale',
      flow3: 'Stratégie',
      flow4: 'Solution pérenne',
      badgeNy: '15 ans à New York',
      badgeCitizen: 'Citoyen américain',
      ctaConsultation: 'Consultation stratégique',
      ctaUsa: 'Pratique USA & Green Card',
    },
    services: {
      title1: 'Solutions juridiques intégrées',
      title2: 'sur mesure',
      desc: 'V. I. LEVIN — cabinet privé d’avocats pour particuliers et entreprises confrontés à des situations complexes aux États-Unis et à l’international.',
      btnAll: 'Toutes les pratiques',
      c1Title: 'USA : Green Card & Citoyenneté',
      c1Code: '#IMMIGRATION & GREEN CARD',
      c1Desc: 'Stratégie sur mesure pour la résidence permanente aux États-Unis : visas talents EB-1A, dispense d’intérêt national EB-2 NIW et naturalisation.',
      c2Title: 'Affaires internationales et contrats transfrontaliers',
      c2Code: '#AFFAIRES INTERNATIONALES',
      c2Desc: 'Structuration sociétaire aux USA (Delaware, Wyoming), au Royaume-Uni, dans l’UE et aux EAU (DIFC / ADGM). Contrats et conformité.',
      c3Title: 'Protection des patrimoines privés, fonds et trusts',
      c3Code: '#PROTECTION D\'ACTIFS & TRUSTS',
      c3Desc: 'Constitution de trusts internationaux irrévocables, sanctuarisation d’actifs face aux créanciers et optimisation fiscale transfrontalière.',
      c4Title: 'Litiges transfrontaliers et arbitrage commercial',
      c4Code: '#ARBITRAGE & CONTENTIEUX',
      c4Desc: 'Défense stratégique lors de litiges commerciaux internationaux, arbitrage international et exécution des décisions de justice étrangères.',
      c5Title: 'Audit des risques juridiques et Due Diligence',
      c5Code: '#AUDIT DES RISQUES',
      c5Desc: 'Examen juridique ligne par ligne des documents avant signature : détection des clauses pièges et vérification rigoureuse des contreparties.',
      c6Title: 'Stratégie transfrontalière sur mesure',
      c6Code: '#STRATÉGIE',
      c6Desc: 'Itinéraire juridique cohérent pour les dossiers complexes au confluent du droit américain et international : Analyze → Strategize → Act.',
    },
    greenCard: {
      badge: 'PRATIQUE AMÉRICAINE D’EXCELLENCE',
      title1: 'USA : Immigration, Citoyenneté',
      title2: 'et Protection du statut',
      desc: '15 ans à New York. Stratégie sur mesure, audit ligne par ligne du formulaire N-400, préparation aux 128 questions du Civics Test.',
      btnTest: 'Test d’immigration',
      btnInterview: 'Entretien consulaire',
      c1Title: 'Green Card & Immigration',
      c1Desc: 'Accompagnement d’excellence vers la résidence permanente : visas de talents EB-1A / EB-2 NIW, ajustement de statut et regroupement.',
      c1Tag: 'Recherché',
      c2Title: 'Citoyenneté américaine',
      c2Desc: 'Suivi juridique d’autorité jusqu’à la prestation de serment et la délivrance du passeport américain.',
      c2Tag: 'Flagship',
      c3Title: 'Civics Test 2026',
      c3Desc: 'Préparation exhaustive aux 128 questions d’histoire, de Constitution et d’institutions des USA avec entraînement oral en anglais.',
      c3Tag: 'Test 2026',
      c4Title: 'Préparation entretien USCIS',
      c4Desc: 'Simulations d’auditions sous pression avec un officier américain : techniques de réponse et élimination des ambiguïtés.',
      c4Tag: 'Mock Interview',
      c5Title: 'Audit du formulaire N-400',
      c5Desc: 'Analyse juridique minutieuse de la demande de naturalisation avant son dépôt officiel pour écarter tout piège procédural.',
      c5Tag: 'Audit risques',
      c6Title: 'Audit et stratégie individuelle',
      c6Desc: 'Évaluation personnalisée de votre éligibilité à la citoyenneté ou à la Green Card avec identification des points sensibles.',
      c6Tag: 'Bespoke',
      gc1Code: '#GREEN CARD',
      gc2Code: '#CITOYENNETÉ USA',
      gc3Code: '#CIVICS TEST 2026',
      gc4Code: '#ENTRETIEN USCIS',
      gc5Code: '#AUDIT N-400',
      gc6Code: '#STRATÉGIE JURIDIQUE',
      stageTitle: '7 étapes de préparation à la citoyenneté américaine',
      s1Title: 'Analyse N-400',
      s1Desc: 'Revue intégrale du formulaire et détection des points de friction potentiels avant envoi.',
      s2Title: 'Questions de l’officier',
      s2Desc: 'Maîtrise des questions types et formulation de réponses juridiquement irréprochables.',
      s3Title: 'Civics Test 2026',
      s3Desc: 'Assimilation approfondie des 128 questions d’histoire et d’instruction civique.',
      s4Title: 'Composante anglaise',
      s4Desc: 'Modules de lecture, écriture et expression orale dissipant toute réserve de l’examinateur.',
      s5Title: 'Audit N-400',
      s5Desc: 'Contrôle préalable des voyages, de la conformité fiscale et de l’historique d’immigration.',
      s6Title: 'Simulation d’entretien',
      s6Desc: 'Mise en situation réelle à fort niveau d’exigence avec débriefing correctif immédiat.',
      s7Title: 'Validation finale',
      s7Desc: 'Dossier probatoire complet, protocole de conduite et feuille de route pour le jour du serment.',
      ctaAudit: 'Démarrer l’audit individuel',
      ctaTest: 'Ouvrir le Civics Test interactif',
    },
    about: {
      title1: 'Solutions juridiques internationales',
      title2: 'de haute précision',
      desc: 'Cabinet d’avocats privé pour dossiers à haute complexité aux États-Unis et dans les grands centres financiers mondiaux. Analyse rigoureuse du droit fédéral et défense intransigeante des intérêts du client.',
      p1Title: '15+ ans de pratique aux États-Unis',
      p1Desc: 'Expertise approfondie en droit fédéral américain et procédures USCIS. Statut direct de citoyen américain et expérience des dossiers délicats.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Secret professionnel institutionnel',
      p2Desc: 'Confidentialité totale selon la norme stricte Attorney-Client Privilege. Protection absolue des informations, pièces et actifs.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Harmonisation des juridictions',
      p3Desc: 'Structuration transfrontalière : USA (Delaware, Wyoming), UE, Royaume-Uni et EAU (DIFC). Neutralisation des conflits fiscaux.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Méthodologie Analyze → Act',
      p4Desc: 'Audit préventif ligne par ligne avant le dépôt de toute demande officielle. Feuille de route précise et exécution ciblée.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Découvrir les principes du cabinet',
    },
    countries: {
      badge: 'GÉOGRAPHIE ET RÉGIMES JURIDIQUES',
      title1: 'Juridictions internationales',
      title2: 'd’intervention',
      desc: 'Compétences au carrefour de traditions juridiques variées. Nous harmonisons les règles de procédure pour préserver vos intérêts.',
      btnAll: 'Toutes les juridictions',
      hub1Name: 'États-Unis',
      hub1Badge: 'Foyer principal',
      hub1System: 'Droit fédéral et droit des États américains',
      hub1Desc: 'Immigration (EB-1A / NIW / Citoyenneté), droit des sociétés du Delaware et Wyoming, contentieux fédéral et statut.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'EAU (DIFC / ADGM)',
      hub2Badge: 'Pôle mondial',
      hub2System: 'Tribunaux du DIFC & Common Law',
      hub2Desc: 'Structuration de sociétés internationales, relocalisation d’actifs, family offices et protection des avoirs à Dubaï.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'Royaume-Uni',
      hub3Badge: 'Common Law',
      hub3System: 'English Common Law',
      hub3Desc: 'Contrats commerciaux de droit anglais, arbitrage londonien, structuration immobilière et trusts transfrontaliers.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'Union Européenne (UE)',
      hub4Badge: 'Droit européen',
      hub4System: 'Civil Law & Règlements européens',
      hub4Desc: 'Accompagnement en Allemagne, France, à Chypre et en Espagne. Conformité des entreprises et gestion des actifs internationaux.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'CORRIDOR :',
    },
    quote: {
      text: '« Le droit n’est pas seulement des lois. C’est le pouvoir de vivre là où vous le désirez. »',
      author: 'V. I. Levin',
    },
    footer: {
      manifesto: 'Cabinet juridique international dédié aux affaires d’exception. Défense des intérêts des clients privés et des entreprises sans frontières.',
      col1: 'Domaines d’intervention',
      s1: 'Immigration et Green Card',
      s2: 'Audit des risques juridiques',
      s3: 'Droit des affaires',
      s4: 'Contrats transfrontaliers',
      s5: 'Famille et successions',
      s6: 'Contentieux et arbitrage',
      col2: 'USA et Juridictions',
      u1: 'Green Card USA (EB-1 / NIW)',
      u2: 'Entretien consulaire',
      u3: 'Test d’immigration',
      u4: 'Juridiction USA',
      u5: 'Allemagne et UE',
      u6: 'EAU (Dubaï / Abou Dabi)',
      u7: 'Chypre (Common Law)',
      col3: 'Cabinet',
      p1: 'Dossiers et jurisprudence',
      p2: 'Articles et analyses',
      p3: 'Manifeste de confidentialité',
      p4: 'Contacts',
      p5: 'Registre interne',
      disclaimerTitle: 'Mentions légales et limitation de responsabilité :',
      disclaimerText: 'Les éléments publiés sur ce site sont à vocation purement informative et ne constituent en aucun cas une consultation juridique engageante ou un démarchage direct. Nous ne délivrons aucune garantie absolue de succès. Pour les procédures nécessitant une représentation devant des cours nationales, nous collaborons avec des avocats inscrits au barreau local concerné.',
      rights: 'Tous droits réservés.',
      motto: '« Vos droits — sans frontières. »',
    },
    modal: {
      title: 'Consultation Stratégique',
      badge: 'ATTORNEY-CLIENT PRIVILEGE · STRICTEMENT CONFIDENTIEL',
      catUsa: 'USA & Green Card',
      catBiz: 'Affaires & Contrats',
      catDisp: 'Litiges & Arbitrage',
      catWealth: 'Actifs & Trusts',
      catOther: 'Autres demandes',
      contactLabel: 'Votre contact pour réponse *',
      contactPlaceholder: '@nom d’utilisateur Telegram ou tél / WhatsApp',
      noteLabel: 'Objet de la demande',
      notePlaceholder: 'Précisez les circonstances clés, juridictions ou échéances...',
      submitBtn: 'Envoyer la demande',
      submitting: 'Transmission en cours...',
      successTitle: 'Demande Enregistrée',
      successDesc: 'Le cabinet V. I. Levin a été notifié. Nous vous recontacterons sous 15 minutes.',
      successBtn: 'Fermer',
      directTg: 'Ou écrivez directement au bot Telegram :',
      errorRequired: 'Veuillez indiquer votre identifiant Telegram, téléphone ou WhatsApp.',
    },
  },
};

interface LanguageContextType {
  currentLang: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (section: string, key: string) => string;
  dict: any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLang, setCurrentLang] = useState<LanguageCode>('ru');

  useEffect(() => {
    try {
      let active: LanguageCode | null = null;
      const savedLang = localStorage.getItem('v_levin_lang') as LanguageCode;
      if (savedLang && ['ru', 'uk', 'en', 'es', 'it', 'fr'].includes(savedLang)) {
        active = savedLang;
      } else if (typeof document !== 'undefined') {
        const match = document.cookie.match(/(?:^|;\s*)v_levin_lang=([a-z]{2})/);
        if (match && ['ru', 'uk', 'en', 'es', 'it', 'fr'].includes(match[1])) {
          active = match[1] as LanguageCode;
        }
      }
      if (active) {
        setCurrentLang(active);
        if (typeof document !== 'undefined') {
          document.documentElement.lang = active;
        }
      }
    } catch {
      // ignore
    }
  }, []);

  const setLanguage = (code: LanguageCode) => {
    setCurrentLang(code);
    try {
      localStorage.setItem('v_levin_lang', code);
      if (typeof document !== 'undefined') {
        document.cookie = `v_levin_lang=${code}; path=/; max-age=31536000; SameSite=Lax`;
        document.documentElement.lang = code;
      }
    } catch {
      // ignore
    }
  };

  const dict = TRANSLATIONS[currentLang] || TRANSLATIONS.ru;

  const t = (section: string, key: string): string => {
    const sec = dict[section];
    if (sec && sec[key]) {
      return sec[key];
    }
    const fallbackSec = TRANSLATIONS.ru[section];
    if (fallbackSec && fallbackSec[key]) {
      return fallbackSec[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, dict }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
