'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'ru' | 'uk' | 'en' | 'es' | 'it' | 'fr';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  name: string;
  flag: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'ru', label: 'RU', name: 'Русский', flag: '/images/flags/ru.svg' },
  { code: 'en', label: 'EN', name: 'English', flag: '/images/flags/en.svg' },
  { code: 'uk', label: 'UA', name: 'Українська', flag: '/images/flags/ua.svg' },
  { code: 'es', label: 'ES', name: 'Español', flag: '/images/flags/es.svg' },
  { code: 'it', label: 'IT', name: 'Italiano', flag: '/images/flags/it.svg' },
  { code: 'fr', label: 'FR', name: 'Français', flag: '/images/flags/fr.svg' },
];

export const TRANSLATIONS: Record<LanguageCode, any> = {
  // ===========================================================================
  // RUSSIAN (RU)
  // ===========================================================================
  ru: {
    nav: {
      services: 'Услуги',
      usaGreenCard: 'США & GREEN CARD',
      jurisdictions: 'Юрисдикции',
      cases: 'Кейсы',
      about: 'О практике',
      faq: 'Частые вопросы',
      contacts: 'Контакты',
      bookConsultation: 'Консультация',
      langTitle: 'Язык / Language',
    },
    hero: {
      badge: 'МЕЖДУНАРОДНАЯ ЮРИДИЧЕСКАЯ ПОМОЩЬ',
      title1: 'Ваши права —',
      title2: 'без границ',
      desc: 'Профессиональная юридическая поддержка для людей и бизнеса в США и по всему миру. Сложная ситуация → точный анализ → стратегия → решение.',
      badgeNy: '15 лет в Нью-Йорке',
      badgeCitizen: 'Гражданин США',
      ctaConsultation: 'РАЗОБРАТЬ МОЮ СИТУАЦИЮ',
      fastContact: 'Быстрая связь через Telegram',
      stat1Num: '15+ лет',
      stat1Title: 'в Нью-Йорке',
      stat1Desc: 'контекст американской среды',
      stat2Num: 'U.S. Citizen',
      stat2Title: 'Гражданин США',
      stat2Desc: 'личное знание системы изнутри',
      stat3Num: 'International',
      stat3Title: 'Трансграничные дела',
      stat3Desc: 'США · Европа · ОАЭ · СНГ',
      stat4Num: '100%',
      stat4Title: 'Конфиденциальность',
      stat4Desc: 'Строгий NDA и защита данных',
    },
    services: {
      tag: 'КОМПЛЕКСНЫЕ РЕШЕНИЯ',
      title1: 'Комплексные юридические решения',
      title2: 'без шаблонов',
      desc: 'V. I. LEVIN — частная практика для людей и бизнеса, которым необходимо разобраться в сложной ситуации, связанной с США или несколькими юрисдикциями.',
      btnAll: 'Все направления практики',
      cardAction: 'Перейти к направлению',
      flagshipBadge: 'Флагман',
      items: [
        {
          num: '01',
          code: 'US IMMIGRATION & STATUS',
          title: 'США: Green Card, EB-1A / NIW & Гражданство',
          desc: 'Индивидуальная стратегия получения статуса резидента США: визы талантов EB-1A, национальные интересы EB-2 NIW, смена статуса и юридический трекинг натурализации.',
          href: '/usa/green-card',
          highlight: true,
        },
        {
          num: '02',
          code: 'CORPORATE & CROSS-BORDER',
          title: 'Международный бизнес и трансграничные контракты',
          desc: 'Корпоративное структурирование в США (Delaware, Wyoming), Великобритании, ЕС и ОАЭ (DIFC / ADGM). Международные контракты и комплаенс.',
          href: '/services/business',
        },
        {
          num: '03',
          code: 'PRIVATE WEALTH & TRUSTS',
          title: 'Защита частных активов, фонды и трасты',
          desc: 'Формирование безотзывных международных трастов, защита капитала от притязаний, безопасное владение активами и трансграничная налоговая защита.',
          href: '/services/legal-consultation',
        },
        {
          num: '04',
          code: 'DISPUTES & ARBITRATION',
          title: 'Трансграничные судебные споры и арбитраж',
          desc: 'Защита интересов частных лиц и компаний в международных коммерческих конфликтах, арбитраж и признание судебных решений в иностранных юрисдикциях.',
          href: '/services/representation',
        },
        {
          num: '05',
          code: 'RISK AUDIT & COMPLIANCE',
          title: 'Аудит юридических рисков и Due Diligence',
          desc: 'Построчный юридический аудит документов до их подписания: выявление ловушек, проверка контрагентов, аудит иммиграционных кейсов и договоров.',
          href: '/services/legal-consultation',
        },
        {
          num: '06',
          code: 'STRATEGIC COUNSEL',
          title: 'Индивидуальная трансграничная стратегия',
          desc: 'Комплексный юридический маршрут для нестандартных ситуаций на стыке американского и международного права по принципу Analyze → Strategize → Act.',
          href: '/contacts',
        },
      ],
    },
    greencard: {
      badge: 'КЛЮЧЕВАЯ ВЕРТИКАЛЬНАЯ ПРАКТИКА',
      title1: 'США: Иммиграция, Гражданство',
      title2: 'и Защита статуса',
      desc: 'Не «репетиторство» и не конвейерное заполнение форм. Мы готовим к прохождению реального американского процесса натурализации с глубоким пониманием системы изнутри.',
      btnEvaluate: 'Оценить шансы на Green Card',
      btnTelegram: 'Telegram-разбор',
      cardAction: 'Узнать подробнее',
      cards: [
        {
          code: 'GREEN CARD',
          title: 'Green Card & Иммиграция',
          desc: 'Индивидуальная стратегия получения статуса резидента: визы талантов EB-1A / EB-2 NIW, смена статуса и семейные петиции.',
          tag: 'Популярное',
        },
        {
          code: 'CITIZENSHIP',
          title: 'Гражданство США',
          desc: 'Комплексный юридический трекинг заявителя до принятия присяги и получения американского паспорта.',
          tag: 'Флагман',
        },
        {
          code: 'CIVICS TEST',
          title: 'Civics Test 2026',
          desc: 'Подготовка к актуальному тесту 2026 года на 128 вопросов: история США, Конституция, устройство органов власти и языковой минимум.',
          tag: '2026 Test',
        },
        {
          code: 'INTERVIEW',
          title: 'Подготовка к интервью USCIS',
          desc: 'Репетиция стресс-собеседований с американским офицером: что спрашивают, как отвечать и как устранить двусмысленности.',
          tag: 'Mock Interview',
        },
        {
          code: 'N-400 AUDIT',
          title: 'Аудит заявления N-400',
          desc: 'Построчный юридический разбор анкеты на натурализацию до её подачи для исключения скрытых процессуальных ловушек.',
          tag: 'Аудит рисков',
        },
        {
          code: 'STRATEGY',
          title: 'Индивидуальный аудит и стратегия',
          desc: 'Персональная оценка шансов на гражданство или Green Card с моделированием критических зон вашего дела.',
          tag: 'Bespoke',
        },
      ],
      methodologyBadge: 'ФИРМЕННАЯ МЕТОДОЛОГИЯ ПОДГОТОВКИ',
      methodologyTitle: '7 этапов подготовки к гражданству США',
      methodologyDesc: 'Не просто заучивание вопросов, а системное устранение слабых мест заявителя до визита в USCIS.',
      stages: [
        { step: '1', title: 'Анализ N-400', desc: 'Построчный разбор анкеты и выявление потенциально проблемных мест до отправки.' },
        { step: '2', title: 'Вопросы офицера', desc: 'Что спрашивает офицер, как корректно формулировать ответы по вашей ситуации.' },
        { step: '3', title: '2026 Civics Test', desc: 'Отработка 128 вопросов по истории и устройству США (до 20 задают, 12 для зачета).' },
        { step: '4', title: 'English Component', desc: 'Подготовка к языковой части интервью: чтение, письмо и разговорные команды.' },
        { step: '5', title: 'Mock Interview', desc: 'Полная имитация настоящего собеседования в формате стресс-тестирования.' },
        { step: '6', title: 'Разбор ошибок', desc: 'Устранение нестыковок и двусмысленностей, вызывающих подозрения офицера.' },
        { step: '7', title: 'Индивидуальная стратегия', desc: 'Финальная подгонка под персональный бэкграунд заявителя.' },
      ],
    },
    about: {
      title1: 'Международные юридические решения',
      title2: 'высокой точности',
      desc: 'Частная юридическая практика для кейсов повышенной сложности в США и глобальных финансовых центрах. Глубокий анализ федеральной правовой системы, нестандартная стратегия и построчная защита интересов доверителя.',
      p1Title: '15+ лет практики в США',
      p1Desc: 'Глубокая экспертиза в федеральном праве и USCIS. Личный статус гражданина США, опыт ведения комплексных иммиграционных кейсов.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Адвокатская тайна',
      p2Desc: 'Институциональная конфиденциальность по стандарту Attorney-Client Privilege. Полная защита данных, документов и активов.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Синхронизация юрисдикций',
      p3Desc: 'Трансграничное структурирование: США (Delaware, Wyoming), ЕС, Великобритания и ОАЭ (DIFC). Нивелирование налоговых коллизий.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Методология Analyze → Act',
      p4Desc: 'Построчный превентивный аудит юридических рисков до подачи любых форм. Выверенная пошаговая дорожная карта защиты интересов.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Подробнее о принципах практики',
    },
    countries: {
      badge: 'ГЕОГРАФИЯ И ПРАВОВЫЕ СИСТЕМЫ',
      title1: 'Международные юрисдикции',
      title2: 'практики',
      desc: 'Компетенции на стыке нескольких правовых систем. Мы синхронизируем процессуальные нормы разных стран для защиты ваших интересов.',
      btnAll: 'Все юрисдикции',
      hub1Name: 'США',
      hub1Badge: 'Ключевой фокус',
      hub1System: 'Федеральное право США & Право штатов',
      hub1Desc: 'Иммиграционный трекинг (EB-1A / NIW / Гражданство), корпоративное право Delaware и Wyoming, федеральный арбитраж и защита статуса.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'ОАЭ (DIFC / ADGM)',
      hub2Badge: 'Трансграничный хаб',
      hub2System: 'DIFC Courts & English Common Law',
      hub2Desc: 'Структурирование международных компаний, релокация капитала, семейные офисы и защита активов в финансовой юрисдикции Дубая.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'Великобритания',
      hub3Badge: 'Английское право',
      hub3System: 'English Common Law',
      hub3Desc: 'Коммерческие контракты по английскому праву, лондонский арбитраж, структурирование владения недвижимостью и трансграничные трасты.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'Европейский Союз (ЕС)',
      hub4Badge: 'Европейское право',
      hub4System: 'Civil Law & Регламенты ЕС',
      hub4Desc: 'Юридическое сопровождение в Германии, Франции, на Кипре и в Испании. Корпоративный комплаенс, санкционные риски и трансграничные активы.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'КОРИДОР:',
    },
    cases: {
      badge: 'ПРАКТИКА И РЕЗУЛЬТАТЫ',
      title: 'Реальные кейсы',
      desc: 'Анонимизированные истории доверителей. Анализ проблемы, выработанная стратегия, конкретные процессуальные шаги и достигнутый результат.',
      btnAll: 'Смотреть все кейсы',
      problemLabel: 'ЮРИДИЧЕСКАЯ ПРОБЛЕМА:',
      solutionLabel: 'ВЫРАБОТАННАЯ СТРАТЕГИЯ:',
      resultLabel: 'ИТОГОВЫЙ РЕЗУЛЬТАТ:',
      similarSituation: 'Похожая ситуация?',
    },
    faq: {
      badge: 'ПРОЗРАЧНОСТЬ И ПОРЯДОК',
      title: 'Частые вопросы доверителей',
      desc: 'Ответы на ключевые вопросы о формате сотрудничества, конфиденциальности, иммиграционном аудите и оплате.',
    },
    contacts: {
      badge: 'ПРЯМОЙ КОНТАКТ',
      title: 'Связаться с практикой',
      desc: 'Первичный разбор проводится строго конфиденциально. Выберите удобный канал коммуникации.',
      scheduleTitle: 'Режим работы практики',
      scheduleDesc: 'Понедельник — Пятница: 09:00 – 20:00 (EST / MSK). Экстренные вопросы доверителей — круглосуточно.',
      tgTitle: 'Защищенный Telegram-бот',
      tgDesc: 'Экспресс-квалификация, отправка документов под защитой адвокатской тайны.',
      btnModal: 'Оставить заявку на разбор ситуации',
    },
    footer: {
      slogan: 'Ваши права — без границ.',
      disclaimer: 'Информация на данном сайте носит исключительно информационный характер и не является публичной офертой. Конфиденциальность гарантируется стандартом Attorney-Client Privilege Rule 1.6.',
      rights: 'Все права защищены.',
      navTitle: 'Навигация',
      contactsTitle: 'Контакты',
    },
  },

  // ===========================================================================
  // ENGLISH (EN)
  // ===========================================================================
  en: {
    nav: {
      services: 'Services',
      usaGreenCard: 'USA & GREEN CARD',
      jurisdictions: 'Jurisdictions',
      cases: 'Cases',
      about: 'About Practice',
      faq: 'FAQ',
      contacts: 'Contacts',
      bookConsultation: 'Consultation',
      langTitle: 'Language',
    },
    hero: {
      badge: 'INTERNATIONAL LEGAL COUNSEL',
      title1: 'Your rights —',
      title2: 'without borders',
      desc: 'Professional legal counsel and institutional defense for individuals and businesses in the US and worldwide. Complex case → surgical analysis → strategy → protected solution.',
      badgeNy: '15 Years in New York',
      badgeCitizen: 'U.S. Citizen',
      ctaConsultation: 'REVIEW MY CASE',
      fastContact: 'Direct Telegram Connection',
      stat1Num: '15+ Years',
      stat1Title: 'in New York',
      stat1Desc: 'native US legal environment',
      stat2Num: 'U.S. Citizen',
      stat2Title: 'Direct Knowledge',
      stat2Desc: 'insider understanding of USCIS',
      stat3Num: 'International',
      stat3Title: 'Cross-Border Scope',
      stat3Desc: 'USA · Europe · UAE · Global',
      stat4Num: '100%',
      stat4Title: 'Confidentiality',
      stat4Desc: 'Strict NDA & Attorney-Client Privilege',
    },
    services: {
      tag: 'PRACTICE AREAS',
      title1: 'Strategic Legal Solutions',
      title2: 'Without Templates',
      desc: 'V. I. LEVIN is a private practice for individuals and businesses navigating high-stakes situations across the US and international jurisdictions.',
      btnAll: 'All Practice Areas',
      cardAction: 'Explore Practice',
      flagshipBadge: 'Flagship',
      items: [
        {
          num: '01',
          code: 'US IMMIGRATION & STATUS',
          title: 'USA: Green Card, EB-1A / NIW & Citizenship',
          desc: 'Individual strategy for US permanent residency: EB-1A extraordinary ability visas, EB-2 National Interest Waivers, status adjustments, and naturalization tracking.',
          href: '/usa/green-card',
          highlight: true,
        },
        {
          num: '02',
          code: 'CORPORATE & CROSS-BORDER',
          title: 'Cross-Border Business & International Contracts',
          desc: 'Corporate structuring in Delaware, Wyoming, UK, EU, and UAE (DIFC / ADGM). Drafting cross-border agreements and compliance programs.',
          href: '/services/business',
        },
        {
          num: '03',
          code: 'PRIVATE WEALTH & TRUSTS',
          title: 'Private Wealth Preservation, Funds & Trusts',
          desc: 'Irrevocable international trusts, creditor protection, multi-jurisdictional asset holding, and cross-border tax defense.',
          href: '/services/legal-consultation',
        },
        {
          num: '04',
          code: 'DISPUTES & ARBITRATION',
          title: 'Cross-Border Disputes & Commercial Arbitration',
          desc: 'Representation in high-conflict international commercial disputes, institutional arbitration, and foreign judgment enforcement.',
          href: '/services/representation',
        },
        {
          num: '05',
          code: 'RISK AUDIT & COMPLIANCE',
          title: 'Legal Risk Audit & Pre-Signing Due Diligence',
          desc: 'Line-by-line scrutiny of critical contracts, counterparty intelligence, and pre-filing immigration case defense audits.',
          href: '/services/legal-consultation',
        },
        {
          num: '06',
          code: 'STRATEGIC COUNSEL',
          title: 'Individual Cross-Border Legal Strategy',
          desc: 'Comprehensive legal roadmaps for unconventional situations spanning US federal law and foreign legal orders: Analyze → Strategize → Act.',
          href: '/contacts',
        },
      ],
    },
    greencard: {
      badge: 'KEY VERTICAL PRACTICE',
      title1: 'USA: Immigration, Citizenship',
      title2: '& Status Defense',
      desc: 'Not "tutoring" or assembly-line paperwork. We prepare clients for the rigorous US naturalization process with deep insider insight into the USCIS system.',
      btnEvaluate: 'Evaluate Green Card Chances',
      btnTelegram: 'Telegram Assessment',
      cardAction: 'Learn More',
      cards: [
        {
          code: 'GREEN CARD',
          title: 'Green Card & Immigration',
          desc: 'Bespoke strategy for permanent resident status: EB-1A extraordinary ability, EB-2 NIW, adjustments, and family petitions.',
          tag: 'Popular',
        },
        {
          code: 'CITIZENSHIP',
          title: 'US Citizenship',
          desc: 'Comprehensive legal roadmap guiding the petitioner up to the oath of allegiance and issuance of the US passport.',
          tag: 'Flagship',
        },
        {
          code: 'CIVICS TEST',
          title: 'Civics Test 2026',
          desc: 'Targeted coaching for the 2026 USCIS 128-question civics examination: US history, Constitution, branches of government, and language proficiency.',
          tag: '2026 Exam',
        },
        {
          code: 'INTERVIEW',
          title: 'USCIS Interview Preparation',
          desc: 'Rigorous mock interviews simulating examiner dynamics: questioning patterns, precise phrasing, and eliminating ambiguities.',
          tag: 'Mock Interview',
        },
        {
          code: 'N-400 AUDIT',
          title: 'N-400 Application Audit',
          desc: 'Line-by-line legal scrutiny of the naturalization petition prior to submission to eradicate hidden procedural traps.',
          tag: 'Risk Audit',
        },
        {
          code: 'STRATEGY',
          title: 'Bespoke Legal Assessment & Strategy',
          desc: 'Confidential qualification evaluation for citizenship or residency with strategic mitigation of high-risk disclosures.',
          tag: 'Bespoke',
        },
      ],
      methodologyBadge: 'PROPRIETARY PREPARATION METHODOLOGY',
      methodologyTitle: '7 Stages of US Citizenship Preparation',
      methodologyDesc: 'Not rote memorization, but systematic remediation of vulnerabilities before setting foot in USCIS.',
      stages: [
        { step: '1', title: 'N-400 Analysis', desc: 'Line-by-line review of the petition to isolate potential red flags prior to filing.' },
        { step: '2', title: 'Officer Inquiries', desc: 'Decoding examiner questioning techniques and mastering legally sound answers.' },
        { step: '3', title: '2026 Civics Test', desc: 'Mastery of all 128 civics questions covering US history, principles, and institutions.' },
        { step: '4', title: 'English Component', desc: 'Drills for reading, writing, and spoken English commands tested during the examination.' },
        { step: '5', title: 'Mock Interview', desc: 'Full-dress stress simulation replicating the exact atmosphere of USCIS field offices.' },
        { step: '6', title: 'Discrepancy Remediation', desc: 'Resolving inconsistencies and ambiguities that trigger officer suspicion.' },
        { step: '7', title: 'Custom Strategy', desc: 'Final strategic alignment customized strictly to the applicant’s unique background.' },
      ],
    },
    about: {
      title1: 'Precision Cross-Border',
      title2: 'Legal Counsel',
      desc: 'Private practice for high-stakes matters spanning the United States and global financial capitals. In-depth mastery of federal legal architecture, non-linear strategy, and rigorous defense of client interests.',
      p1Title: '15+ Years in New York',
      p1Desc: 'Extensive federal litigation and USCIS regulatory acumen. Personal US citizen standing with hands-on command of the American system.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Privileged Confidentiality',
      p2Desc: 'Institutional secrecy protected under Attorney-Client Privilege. Absolute security for client files, communications, and assets.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Multi-Jurisdictional Alignment',
      p3Desc: 'Cross-border harmonization: US (Delaware, Wyoming), EU, UK, and UAE (DIFC). Mitigating tax and jurisdictional friction.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Analyze → Act Standard',
      p4Desc: 'Line-by-line pre-filing risk assessment before submitting any documents. Surgical procedural execution for zero-defect results.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Explore Practice Principles',
    },
    countries: {
      badge: 'GEOGRAPHY & LEGAL SYSTEMS',
      title1: 'International Jurisdictions',
      title2: 'of Practice',
      desc: 'Interdisciplinary expertise bridging Common Law and Civil Law. We synchronize legal procedures across multiple states to secure your rights.',
      btnAll: 'All Jurisdictions',
      hub1Name: 'United States',
      hub1Badge: 'Primary Focus',
      hub1System: 'US Federal Law & State Jurisdictions',
      hub1Desc: 'Immigration tracking (EB-1A / NIW / Citizenship), Delaware & Wyoming corporate formations, federal litigation, and status defense.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'UAE (DIFC / ADGM)',
      hub2Badge: 'Cross-Border Hub',
      hub2System: 'DIFC Courts & English Common Law',
      hub2Desc: 'International holding structures, capital relocation, family offices, and wealth defense within Dubai’s financial common law hub.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'United Kingdom',
      hub3Badge: 'English Law',
      hub3System: 'English Common Law',
      hub3Desc: 'English law commercial contracts, London arbitration, international property holding vehicles, and cross-border trusts.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'European Union (EU)',
      hub4Badge: 'European Law',
      hub4System: 'Civil Law & EU Directives',
      hub4Desc: 'Legal counsel across Germany, France, Cyprus, and Spain. Corporate compliance, sanctions risk management, and asset security.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'CORRIDOR:',
    },
    cases: {
      badge: 'CASE STUDIES & RESULTS',
      title: 'Featured Case Results',
      desc: 'Redacted client histories: risk analysis, bespoke procedural strategy, and binding resolution across borders.',
      btnAll: 'View All Cases',
      problemLabel: 'LEGAL CONFLICT:',
      solutionLabel: 'STRATEGY & RESOLUTION:',
      resultLabel: 'CERTIFIED RESULT:',
      similarSituation: 'Have a similar matter?',
    },
    faq: {
      badge: 'STANDARDS & TRANSPARENCY',
      title: 'Frequently Asked Questions',
      desc: 'Direct answers regarding engagement protocols, jurisdictions, and settlements.',
    },
    contacts: {
      badge: 'DIRECT CONTACT',
      title: 'Contact the Practice',
      desc: 'Initial risk assessments are conducted under strict privilege. Select your preferred channel.',
      scheduleTitle: 'Practice Hours',
      scheduleDesc: 'Monday — Friday: 09:00 – 20:00 (EST). Urgent client matters — 24/7 on retainer.',
      tgTitle: 'Secure Telegram Gateway',
      tgDesc: 'Direct qualification and encrypted document transmission.',
      btnModal: 'Request Case Review',
    },
    footer: {
      slogan: 'Your rights — without borders.',
      disclaimer: 'The information on this website is for informational purposes only and does not constitute a public offer. Confidentiality is safeguarded under Attorney-Client Privilege Rule 1.6.',
      rights: 'All rights reserved.',
      navTitle: 'Navigation',
      contactsTitle: 'Contacts',
    },
  },

  // ===========================================================================
  // UKRAINIAN (UK)
  // ===========================================================================
  uk: {
    nav: {
      services: 'Послуги',
      usaGreenCard: 'США & GREEN CARD',
      jurisdictions: 'Юрисдикції',
      cases: 'Кейси',
      about: 'Про практику',
      faq: 'Часті питання',
      contacts: 'Контакти',
      bookConsultation: 'Консультація',
      langTitle: 'Мова / Language',
    },
    hero: {
      badge: 'МІЖНАРОДНА ПРАВОВА ДОПОМОГА',
      title1: 'Ваші права —',
      title2: 'без кордонів',
      desc: 'Професійна юридична підтримка для людей та бізнесу в США та по всьому світу. Складна ситуація → точний аналіз → стратегія → захищене рішення.',
      badgeNy: '15 років у Нью-Йорку',
      badgeCitizen: 'Громадянин США',
      ctaConsultation: 'РОЗІБРАТИ МОЮ СИТУАЦІЮ',
      fastContact: 'Прямий зв’язок у Telegram',
      stat1Num: '15+ років',
      stat1Title: 'у Нью-Йорку',
      stat1Desc: 'американське правове середовище',
      stat2Num: 'U.S. Citizen',
      stat2Title: 'Громадянин США',
      stat2Desc: 'розуміння системи зсередини',
      stat3Num: 'International',
      stat3Title: 'Транскордонні справи',
      stat3Desc: 'США · Європа · ОАЕ · Світ',
      stat4Num: '100%',
      stat4Title: 'Конфіденційність',
      stat4Desc: 'Суворий NDA та захист даних',
    },
    services: {
      tag: 'КОМПЛЕКСНІ РІШЕННЯ',
      title1: 'Комплексні юридичні рішення',
      title2: 'без шаблонів',
      desc: 'V. I. LEVIN — приватна практика для людей та бізнесу, яким необхідно розібратися у складній ситуації в США або кількох юрисдикціях.',
      btnAll: 'Всі напрями практики',
      cardAction: 'Перейти до напряму',
      flagshipBadge: 'Флагман',
      items: [
        {
          num: '01',
          code: 'US IMMIGRATION & STATUS',
          title: 'США: Green Card, EB-1A / NIW & Громадянство',
          desc: 'Індивідуальна стратегія отримання статусу резидента США: візи талантів EB-1A, національні інтереси EB-2 NIW, зміна статусу та трекінг натуралізації.',
          href: '/usa/green-card',
          highlight: true,
        },
        {
          num: '02',
          code: 'CORPORATE & CROSS-BORDER',
          title: 'Міжнародний бізнес та транскордонні контракти',
          desc: 'Корпоративне структурування в США (Delaware, Wyoming), Великобританії, ЄС та ОАЕ (DIFC / ADGM). Контракти та комплаєнс.',
          href: '/services/business',
        },
        {
          num: '03',
          code: 'PRIVATE WEALTH & TRUSTS',
          title: 'Захист приватних активів, фонди та трасти',
          desc: 'Формування безвідкличних міжнародних трастів, захист капіталу від домагань, безпечне володіння активами та податковий захист.',
          href: '/services/legal-consultation',
        },
        {
          num: '04',
          code: 'DISPUTES & ARBITRATION',
          title: 'Транскордонні судові спори та арбітраж',
          desc: 'Захист інтересів приватних осіб та компаній у міжнародних комерційних конфліктах, арбітраж і визнання судових рішень.',
          href: '/services/representation',
        },
        {
          num: '05',
          code: 'RISK AUDIT & COMPLIANCE',
          title: 'Аудит юридичних ризиків та Due Diligence',
          desc: 'Построковий аудит документів до їх підписання: виявлення пасток, перевірка контрагентів, аудит імміграційних кейсів.',
          href: '/services/legal-consultation',
        },
        {
          num: '06',
          code: 'STRATEGIC COUNSEL',
          title: 'Індивідуальна транскордонна стратегія',
          desc: 'Комплексний юридичний маршрут для нестандартних ситуацій на стику американського та міжнародного права за принципом Analyze → Act.',
          href: '/contacts',
        },
      ],
    },
    greencard: {
      badge: 'КЛЮЧОВА ВЕРТИКАЛЬНА ПРАКТИКА',
      title1: 'США: Імміграція, Громадянство',
      title2: 'та Захист статусу',
      desc: 'Не «репетиторство» і не конвеєрне заповнення форм. Ми готуємо до проходження реального американського процесу натуралізації з глибоким розумінням системи зсередини.',
      btnEvaluate: 'Оцінити шанси на Green Card',
      btnTelegram: 'Telegram-розбір',
      cardAction: 'Дізнатися більше',
      cards: [
        {
          code: 'GREEN CARD',
          title: 'Green Card та Імміграція',
          desc: 'Індивідуальна стратегія отримання статусу резидента: візи талантів EB-1A / EB-2 NIW, зміна статусу та сімейні петиції.',
          tag: 'Популярне',
        },
        {
          code: 'CITIZENSHIP',
          title: 'Громадянство США',
          desc: 'Комплексний юридичний супровід заявника до складання присяги та отримання американського паспорта.',
          tag: 'Флагман',
        },
        {
          code: 'CIVICS TEST',
          title: 'Civics Test 2026',
          desc: 'Підготовка до оновленого тесту 2026 року на 128 запитань: історія США, Конституція, державний устрій та мовний мінімум.',
          tag: 'Тест 2026',
        },
        {
          code: 'INTERVIEW',
          title: 'Підготовка до інтерв’ю USCIS',
          desc: 'Репетиція стрес-співбесід з американським офіцером: типи запитань, коректні відповіді та усунення двозначностей.',
          tag: 'Симуляція',
        },
        {
          code: 'N-400 AUDIT',
          title: 'Аудит заяви N-400',
          desc: 'Построковий юридичний аналіз анкети на натуралізацію до її подання для виключення прихованих процесуальних пасток.',
          tag: 'Аудит ризиків',
        },
        {
          code: 'STRATEGY',
          title: 'Індивідуальний аудит і стратегія',
          desc: 'Персональна оцінка шансів на громадянство або Green Card з моделюванням критичних зон вашої справи.',
          tag: 'Персонально',
        },
      ],
      methodologyBadge: 'ФІРМОВА МЕТОДОЛОГІЯ ПІДГОТОВКИ',
      methodologyTitle: '7 етапів підготовки до громадянства США',
      methodologyDesc: 'Не просте заучування питань, а системне усунення слабких місць заявника до візиту в USCIS.',
      stages: [
        { step: '1', title: 'Аналіз N-400', desc: 'Построковий розбір анкети та виявлення потенційно проблемних місць до відправки.' },
        { step: '2', title: 'Запитання офіцера', desc: 'Що запитує офіцер, як коректно формулювати відповіді щодо вашої ситуації.' },
        { step: '3', title: '2026 Civics Test', desc: 'Відпрацювання 128 питань з історії та устрою США (до 20 ставлять, 12 для заліку).' },
        { step: '4', title: 'English Component', desc: 'Підготовка до мовної частини інтерв’ю: читання, письмо та розмовні команди.' },
        { step: '5', title: 'Mock Interview', desc: 'Повна імітація справжньої співбесіди у форматі стрес-тестування.' },
        { step: '6', title: 'Розбір помилок', desc: 'Усунення нестиковок і двозначностей, що викликають підозри офіцера.' },
        { step: '7', title: 'Індивідуальна стратегія', desc: 'Фінальне налаштування під персональний бекграунд заявника.' },
      ],
    },
    about: {
      title1: 'Міжнародні юридичні рішення',
      title2: 'високої точності',
      desc: 'Приватна юридична практика для справ підвищеної складності в США та ключових фінансових центрах. Глибокий аналіз федеральної правової системи, нестандартна стратегія та захист інтересів клієнта.',
      p1Title: '15+ років практики в США',
      p1Desc: 'Глибока експертиза у федеральному праві та USCIS. Статус громадянина США, досвід ведення комплексних імміграційних справ.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Адвокатська таємниця',
      p2Desc: 'Інституційна конфіденційність за стандартом Attorney-Client Privilege. Повний захист даних, документів та активів.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Синхронізація юрисдикцій',
      p3Desc: 'Транскордонне структурування: США (Delaware, Wyoming), ЄС, Великобританія та ОАЕ (DIFC). Нівелювання податкових колізій.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Методологія Analyze → Act',
      p4Desc: 'Построковий превентивний аудит юридичних ризиків до подання будь-яких форм. Вивірена дорожня карта захисту інтересів.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Детальніше про принципи практики',
    },
    countries: {
      badge: 'ГЕОГРАФІЯ ТА ПРАВОВІ СИСТЕМИ',
      title1: 'Міжнародні юрисдикції',
      title2: 'практики',
      desc: 'Компетенції на стику кількох правових систем. Ми синхронізуємо процесуальні норми різних країн для захисту ваших інтересів.',
      btnAll: 'Всі юрисдикції',
      hub1Name: 'США',
      hub1Badge: 'Ключовий фокус',
      hub1System: 'Федеральне право США & Право штатів',
      hub1Desc: 'Імміграційний трекінг (EB-1A / NIW / Громадянство), корпоративне право Delaware та Wyoming, федеральний арбітраж.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'ОАЕ (DIFC / ADGM)',
      hub2Badge: 'Транскордонний хаб',
      hub2System: 'DIFC Courts & English Common Law',
      hub2Desc: 'Структурування міжнародних компаній, релокація капіталу, сімейні офіси та захист активів у фінансовій юрисдикції Дубая.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'Великобританія',
      hub3Badge: 'Англійське право',
      hub3System: 'English Common Law',
      hub3Desc: 'Комерційні контракти за англійським правом, лондонський арбітраж, структурування володіння нерухомістю та трасти.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'Європейський Союз (ЄС)',
      hub4Badge: 'Європейське право',
      hub4System: 'Civil Law & Регламенти ЄС',
      hub4Desc: 'Юридичний супровід у Німеччині, Франції, на Кіпрі та в Іспанії. Корпоративний комплаєнс, санкційні ризики та активи.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'КОРИДОР:',
    },
    cases: {
      badge: 'ПРАКТИКА ТА РЕЗУЛЬТАТИ',
      title: 'Реальні кейси',
      desc: 'Анонімізовані історії клієнтів: аналіз проблеми, вироблена стратегія, процесуальні кроки та досягнутий результат.',
      btnAll: 'Дивитися всі кейси',
      problemLabel: 'ЮРИДИЧНА ПРОБЛЕМА:',
      solutionLabel: 'ВИРОБЛЕНА СТРАТЕГІЯ:',
      resultLabel: 'ПІДСУМКОВИЙ РЕЗУЛЬТАТ:',
      similarSituation: 'Схожа ситуація?',
    },
    faq: {
      badge: 'ПРОЗОРІСТЬ ТА СТАНДАРТИ',
      title: 'Часті запитання',
      desc: 'Відповіді на ключові питання щодо формату роботи, юрисдикцій та розрахунків.',
    },
    contacts: {
      badge: 'ПРЯМИЙ КОНТАКТ',
      title: 'Зв’язатися з практикою',
      desc: 'Первинний аналіз проводиться суворо конфіденційно. Оберіть зручний канал зв’язку.',
      scheduleTitle: 'Режим роботи практики',
      scheduleDesc: 'Понеділок — П’ятниця: 09:00 – 20:00 (EST). Екстрені питання — цілодобово за договором.',
      tgTitle: 'Захищений Telegram-бот',
      tgDesc: 'Експрес-кваліфікація та безпечна передача документів.',
      btnModal: 'Залишити заявку на розбір',
    },
    footer: {
      slogan: 'Ваші права — без кордонів.',
      disclaimer: 'Інформація на цьому сайті має виключно ознайомлювальний характер. Конфіденційність захищена адвокатською таємницею Rule 1.6.',
      rights: 'Всі права захищені.',
      navTitle: 'Навігація',
      contactsTitle: 'Контакти',
    },
  },

  // ===========================================================================
  // SPANISH (ES)
  // ===========================================================================
  es: {
    nav: {
      services: 'Servicios',
      usaGreenCard: 'EE. UU. & GREEN CARD',
      jurisdictions: 'Jurisdicciones',
      cases: 'Casos',
      about: 'Práctica Legal',
      faq: 'Preguntas',
      contacts: 'Contacto',
      bookConsultation: 'Consulta',
      langTitle: 'Idioma / Language',
    },
    hero: {
      badge: 'ASESORÍA JURÍDICA INTERNACIONAL',
      title1: 'Sus derechos —',
      title2: 'sin fronteras',
      desc: 'Asesoramiento legal de primer nivel y defensa institucional para personas y empresas en EE. UU. y a nivel global. Asunto complejo → análisis quirúrgico → estrategia → solución protegida.',
      badgeNy: '15 años en Nueva York',
      badgeCitizen: 'Ciudadano de EE. UU.',
      ctaConsultation: 'ANALIZAR MI SITUACIÓN',
      fastContact: 'Contacto directo por Telegram',
      stat1Num: '15+ Años',
      stat1Title: 'en Nueva York',
      stat1Desc: 'entorno legal estadounidense',
      stat2Num: 'U.S. Citizen',
      stat2Title: 'Ciudadano de EE. UU.',
      stat2Desc: 'visión interna de USCIS',
      stat3Num: 'International',
      stat3Title: 'Casos Transfronterizos',
      stat3Desc: 'EE. UU. · Europa · EAU · Global',
      stat4Num: '100%',
      stat4Title: 'Confidencialidad',
      stat4Desc: 'Estricto secreto profesional (NDA)',
    },
    services: {
      tag: 'SOLUCIONES INTEGRALES',
      title1: 'Soluciones jurídicas estratégicas',
      title2: 'sin plantillas',
      desc: 'V. I. LEVIN es una práctica privada para particulares y corporaciones que afrontan situaciones complejas en EE. UU. o múltiples jurisdicciones.',
      btnAll: 'Todas las áreas de práctica',
      cardAction: 'Ver área de práctica',
      flagshipBadge: 'Insignia',
      items: [
        {
          num: '01',
          code: 'US IMMIGRATION & STATUS',
          title: 'EE. UU.: Green Card, EB-1A / NIW y Ciudadanía',
          desc: 'Estrategia personalizada para la residencia permanente en EE. UU.: visados de talento extraordinario EB-1A, EB-2 NIW, ajuste de estatus y naturalización.',
          href: '/usa/green-card',
          highlight: true,
        },
        {
          num: '02',
          code: 'CORPORATE & CROSS-BORDER',
          title: 'Empresas Transfronterizas y Contratos Internacionales',
          desc: 'Estructuración societaria en EE. UU. (Delaware, Wyoming), Reino Unido, UE y EAU (DIFC). Contratación transfronteriza y cumplimiento normativo.',
          href: '/services/business',
        },
        {
          num: '03',
          code: 'PRIVATE WEALTH & TRUSTS',
          title: 'Protección Patrimonial Privada, Fondos y Fideicomisos',
          desc: 'Constitución de fideicomisos irrevocables internacionales, blindaje de activos frente a acreedores y defensa fiscal internacional.',
          href: '/services/legal-consultation',
        },
        {
          num: '04',
          code: 'DISPUTES & ARBITRATION',
          title: 'Litigios Transfronterizos y Arbitraje Comercial',
          desc: 'Defensa de intereses corporativos y patrimoniales en conflictos internacionales, arbitraje comercial y ejecución de sentencias extranjeras.',
          href: '/services/representation',
        },
        {
          num: '05',
          code: 'RISK AUDIT & COMPLIANCE',
          title: 'Auditoría de Riesgos Legales y Due Diligence',
          desc: 'Revisión jurídica exhaustiva línea por línea antes de firmar contratos: detección de contingencias y auditoría de expedientes migratorios.',
          href: '/services/legal-consultation',
        },
        {
          num: '06',
          code: 'STRATEGIC COUNSEL',
          title: 'Estrategia Jurídica Internacional a Medida',
          desc: 'Planificación legal integral para situaciones atípicas en la intersección del derecho federal estadounidense e internacional.',
          href: '/contacts',
        },
      ],
    },
    greencard: {
      badge: 'PRÁCTICA VERTICAL CLAVE',
      title1: 'EE. UU.: Inmigración, Ciudadanía',
      title2: 'y Defensa de Estatus',
      desc: 'Ni "tutorías" ni cumplimentación mecánica de formularios. Preparamos para el verdadero proceso de naturalización de EE. UU. con conocimiento interno de USCIS.',
      btnEvaluate: 'Evaluar opciones de Green Card',
      btnTelegram: 'Análisis en Telegram',
      cardAction: 'Conocer más',
      cards: [
        {
          code: 'GREEN CARD',
          title: 'Green Card e Inmigración',
          desc: 'Estrategia personalizada para residencia permanente: EB-1A talento, EB-2 NIW, ajuste de estatus y peticiones familiares.',
          tag: 'Popular',
        },
        {
          code: 'CITIZENSHIP',
          title: 'Ciudadanía de EE. UU.',
          desc: 'Supervisión legal integral hasta el juramento de lealtad y la emisión del pasaporte estadounidense.',
          tag: 'Insignia',
        },
        {
          code: 'CIVICS TEST',
          title: 'Examen Cívico 2026',
          desc: 'Preparación para el temario oficial 2026 de 128 preguntas: historia de EE. UU., Constitución, poderes federales y suficiencia de inglés.',
          tag: 'Test 2026',
        },
        {
          code: 'INTERVIEW',
          title: 'Preparación para la Entrevista USCIS',
          desc: 'Simulacro intensivo de entrevista con oficiales de inmigración: formulación de respuestas precisas y neutralización de inconsistencias.',
          tag: 'Simulacro',
        },
        {
          code: 'N-400 AUDIT',
          title: 'Auditoría del Formulario N-400',
          desc: 'Revisión jurídica exhaustiva línea por línea antes de la presentación oficial para evitar denegaciones o dilaciones.',
          tag: 'Auditoría',
        },
        {
          code: 'STRATEGY',
          title: 'Auditoría Individual y Estrategia',
          desc: 'Evaluación personalizada de viabilidad para residencia o ciudadanía con simulación preventiva de escenarios de riesgo.',
          tag: 'A Medida',
        },
      ],
      methodologyBadge: 'METODOLOGÍA EXCLUSIVA DE PREPARACIÓN',
      methodologyTitle: '7 etapas de preparación para la ciudadanía estadounidense',
      methodologyDesc: 'No es memorización pasiva, sino subsanación sistemática de puntos vulnerables antes de comparecer ante USCIS.',
      stages: [
        { step: '1', title: 'Análisis N-400', desc: 'Revisión minuciosa de cada campo para subsanar cualquier incoherencia previa.' },
        { step: '2', title: 'Preguntas del Oficial', desc: 'Identificación de las líneas de interrogatorio del oficial y formulación jurídica precisa.' },
        { step: '3', title: 'Examen Cívico 2026', desc: 'Dominio de las 128 preguntas oficiales de historia y gobierno de EE. UU.' },
        { step: '4', title: 'Componente de Inglés', desc: 'Práctica dirigida de lectura, escritura y vocabulario de mandatos procesales.' },
        { step: '5', title: 'Simulacro de Entrevista', desc: 'Ensayo en condiciones de estrés idénticas a la comparecencia ante USCIS.' },
        { step: '6', title: 'Corrección de Errores', desc: 'Eliminación de cualquier ambigüedad susceptible de despertar sospechas.' },
        { step: '7', title: 'Estrategia Personalizada', desc: 'Ajuste definitivo conforme al perfil probatorio de cada solicitante.' },
      ],
    },
    about: {
      title1: 'Soluciones Jurídicas',
      title2: 'de Alta Precisión',
      desc: 'Práctica legal privada para asuntos de alta complejidad en EE. UU. y centros financieros globales. Análisis profundo del ordenamiento federal, estrategia procesal y defensa del cliente.',
      p1Title: '15+ años en EE. UU.',
      p1Desc: 'Profundo conocimiento del derecho federal y normativa USCIS. Condición personal de ciudadano estadounidense.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Secreto Profesional',
      p2Desc: 'Confidencialidad amparada por Attorney-Client Privilege. Salvaguarda integral de expedientes y patrimonio.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Sincronización Jurisdiccional',
      p3Desc: 'Estructuración societaria: EE. UU. (Delaware, Wyoming), UE, Reino Unido y EAU (DIFC). Prevención de colisiones fiscales.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Metodología Analyze → Act',
      p4Desc: 'Auditoría preventiva de riesgos antes de la presentación de cualquier solicitud oficial.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Conozca los principios de la práctica',
    },
    countries: {
      badge: 'GEOGRAFÍA Y SISTEMAS LEGALES',
      title1: 'Jurisdicciones Internacionales',
      title2: 'de Intervención',
      desc: 'Competencias en la encrucijada de sistemas de Common Law y Civil Law. Sincronizamos normas procesales de diversos Estados.',
      btnAll: 'Todas las jurisdicciones',
      hub1Name: 'Estados Unidos',
      hub1Badge: 'Foco Principal',
      hub1System: 'Derecho Federal y Estatal de EE. UU.',
      hub1Desc: 'Inmigración (EB-1A / NIW / Ciudadanía), sociedades en Delaware y Wyoming, arbitraje federal y defensa de estatus.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'EAU (DIFC / ADGM)',
      hub2Badge: 'Hub Financiero',
      hub2System: 'Tribunales DIFC y Common Law',
      hub2Desc: 'Sociedades holding internacionales, deslocalización patrimonial y oficinas familiares en Dubái.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'Reino Unido',
      hub3Badge: 'Derecho Inglés',
      hub3System: 'English Common Law',
      hub3Desc: 'Contratación mercantil bajo derecho inglés, arbitraje en Londres y fideicomisos transfronterizos.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'Unión Europea (UE)',
      hub4Badge: 'Derecho Europeo',
      hub4System: 'Civil Law y Reglamentos UE',
      hub4Desc: 'Asesoramiento legal en Alemania, Francia, Chipre y España. Cumplimiento normativo y gestión de riesgos sancionadores.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'CORREDOR:',
    },
    cases: {
      badge: 'JURISPRUDENCIA Y RESULTADOS',
      title: 'Casos Reales',
      desc: 'Historiales anonimizados: análisis del riesgo, estrategia procesal a medida y resolución obtenida.',
      btnAll: 'Ver todos los casos',
      problemLabel: 'CONFLICTO LEGAL:',
      solutionLabel: 'ESTRATEGIA Y RESOLUCIÓN:',
      resultLabel: 'RESULTADO OBTENIDO:',
      similarSituation: '¿Tiene un caso similar?',
    },
    faq: {
      badge: 'TRANSPARENCIA Y RIGOR',
      title: 'Preguntas frecuentes',
      desc: 'Respuestas sobre metodología, jurisdicciones y modalidades de pago.',
    },
    contacts: {
      badge: 'CONTACTO DIRECTO',
      title: 'Contactar con la Práctica',
      desc: 'La evaluación preliminar se realiza bajo estricto secreto profesional. Elija el canal de su preferencia.',
      scheduleTitle: 'Horario de Atención',
      scheduleDesc: 'Lunes a Viernes: 09:00 – 20:00 (EST). Urgencias de clientes con contrato: 24/7.',
      tgTitle: 'Bot Seguro de Telegram',
      tgDesc: 'Cualificación rápida y envío cifrado de expedientes.',
      btnModal: 'Solicitar análisis del caso',
    },
    footer: {
      slogan: 'Sus derechos — sin fronteras.',
      disclaimer: 'La información de este sitio tiene carácter exclusivamente informativo. Confidencialidad garantizada bajo Attorney-Client Privilege Rule 1.6.',
      rights: 'Todos los derechos reservados.',
      navTitle: 'Navegación',
      contactsTitle: 'Contacto',
    },
  },

  // ===========================================================================
  // ITALIAN (IT)
  // ===========================================================================
  it: {
    nav: {
      services: 'Servizi',
      usaGreenCard: 'USA & GREEN CARD',
      jurisdictions: 'Giurisdizioni',
      cases: 'Casi',
      about: 'La Pratica',
      faq: 'Domande',
      contacts: 'Contatti',
      bookConsultation: 'Consulenza',
      langTitle: 'Lingua / Language',
    },
    hero: {
      badge: 'ASSISTENZA LEGALE INTERNAZIONALE',
      title1: 'I vostri diritti —',
      title2: 'senza frontiere',
      desc: 'Assistenza legale d’eccellenza e tutela istituzionale per privati e imprese negli Stati Uniti e nel mondo. Caso complesso → analisi chirurgica → strategia → soluzione vincolante.',
      badgeNy: '15 anni a New York',
      badgeCitizen: 'Cittadino USA',
      ctaConsultation: 'ANALISI DEL MIO CASO',
      fastContact: 'Contatto diretto su Telegram',
      stat1Num: '15+ Anni',
      stat1Title: 'a New York',
      stat1Desc: 'ambiente giuridico statunitense',
      stat2Num: 'U.S. Citizen',
      stat2Title: 'Cittadino USA',
      stat2Desc: 'conoscenza diretta di USCIS',
      stat3Num: 'International',
      stat3Title: 'Casi Transfrontalieri',
      stat3Desc: 'USA · Europa · EAU · Globale',
      stat4Num: '100%',
      stat4Title: 'Riservatezza',
      stat4Desc: 'Patto di segretezza (NDA)',
    },
    services: {
      tag: 'SOLUZIONI INTEGRATE',
      title1: 'Soluzioni legali strategiche',
      title2: 'senza standardizzazioni',
      desc: 'V. I. LEVIN è una pratica legale privata per clienti e imprese che devono risolvere questioni complesse negli USA o in più ordinamenti giuridici.',
      btnAll: 'Tutte le aree di attività',
      cardAction: 'Approfondisci l’area',
      flagshipBadge: 'Punta',
      items: [
        {
          num: '01',
          code: 'US IMMIGRATION & STATUS',
          title: 'USA: Green Card, EB-1A / NIW & Cittadinanza',
          desc: 'Strategia individuale per la residenza permanente USA: visti per abilità straordinarie EB-1A, interesse nazionale EB-2 NIW, cambi di status e naturalizzazione.',
          href: '/usa/green-card',
          highlight: true,
        },
        {
          num: '02',
          code: 'CORPORATE & CROSS-BORDER',
          title: 'Business Internazionale e Contrattualistica Estera',
          desc: 'Costituzione societaria in Delaware, Wyoming, UK, UE ed EAU (DIFC). Redazione di accordi commerciali transfrontalieri e compliance.',
          href: '/services/business',
        },
        {
          num: '03',
          code: 'PRIVATE WEALTH & TRUSTS',
          title: 'Tutela Patrimoniale, Trust e Fondazioni',
          desc: 'Creazione di trust internazionali irrevocabili, protezione del patrimonio da aggressioni legali e ottimizzazione fiscale estera.',
          href: '/services/legal-consultation',
        },
        {
          num: '04',
          code: 'DISPUTES & ARBITRATION',
          title: 'Contenzioso Transfrontaliero e Arbitrato Commerciale',
          desc: 'Difesa degli interessi in controversie transnazionali complesse, arbitrati internazionali e riconoscimento di sentenze estere.',
          href: '/services/representation',
        },
        {
          num: '05',
          code: 'RISK AUDIT & COMPLIANCE',
          title: 'Audit dei Rischi Giuridici e Due Diligence',
          desc: 'Verifica riga per riga di contratti strategici prima della sottoscrizione per disinnescare clausole pregiudizievoli.',
          href: '/services/legal-consultation',
        },
        {
          num: '06',
          code: 'STRATEGIC COUNSEL',
          title: 'Strategia Legale Transfrontaliera su Misura',
          desc: 'Pianificazione giuridica ad alto livello per fattispecie non convenzionali tra diritto federale USA e ordinamenti esteri.',
          href: '/contacts',
        },
      ],
    },
    greencard: {
      badge: 'AREA DI PRATICA VERTICALE',
      title1: 'USA: Immigrazione, Cittadinanza',
      title2: 'e Difesa dello Status',
      desc: 'Né "ripetizioni" né moduli compilati in serie. Prepariamo al vero percorso di naturalizzazione USA con una profonda comprensione interna dell’USCIS.',
      btnEvaluate: 'Valuta le probabilità Green Card',
      btnTelegram: 'Analisi Telegram',
      cardAction: 'Scopri di più',
      cards: [
        {
          code: 'GREEN CARD',
          title: 'Green Card & Immigrazione',
          desc: 'Strategia personalizzata per residenza permanente: visti straordinari EB-1A / EB-2 NIW, cambi di status e ricongiungimenti.',
          tag: 'Richiesto',
        },
        {
          code: 'CITIZENSHIP',
          title: 'Cittadinanza Statunitense',
          desc: 'Assistenza legale continuativa fino al giuramento di fedeltà e al rilascio del passaporto USA.',
          tag: 'Punta',
        },
        {
          code: 'CIVICS TEST',
          title: 'Test Civico 2026',
          desc: 'Preparazione intensiva per il test USCIS 2026 su 128 domande: storia, Costituzione, istituzioni federali e competenza linguistica.',
          tag: 'Test 2026',
        },
        {
          code: 'INTERVIEW',
          title: 'Preparazione al Colloquio USCIS',
          desc: 'Simulazioni realistiche del colloquio con l’ufficiale federale: domande critiche, risposte idonee ed eliminazione dei dubbi.',
          tag: 'Simulazione',
        },
        {
          code: 'N-400 AUDIT',
          title: 'Revisione Modulo N-400',
          desc: 'Verifica legale riga per riga della domanda di naturalizzazione prima del deposito per scongiurare vizi procedurali.',
          tag: 'Audit Rischi',
        },
        {
          code: 'STRATEGY',
          title: 'Strategia e Diagnosi Individuale',
          desc: 'Valutazione preliminare di ammissibilità per Green Card o cittadinanza con mappatura preventiva dei rischi.',
          tag: 'Su Misura',
        },
      ],
      methodologyBadge: 'METODOLOGIA PROPRIETARIA DI PREPARAZIONE',
      methodologyTitle: 'I 7 passaggi di preparazione alla cittadinanza USA',
      methodologyDesc: 'Non semplice memorizzazione, ma eliminazione mirata di ogni fattore critico prima dell’incontro con l’USCIS.',
      stages: [
        { step: '1', title: 'Analisi N-400', desc: 'Scansione dettagliata dell’istanza per neutralizzare ogni incongruenza formale.' },
        { step: '2', title: 'Quesiti dell’Ufficiale', desc: 'Decodifica dei modelli di interrogatorio dell’USCIS e formulazione corretta delle risposte.' },
        { step: '3', title: 'Test Civico 2026', desc: 'Studio ragionato delle 128 domande federali su storia e ordinamento istituzionale.' },
        { step: '4', title: 'Competenza Linguistica', desc: 'Allenamento mirato su lettura, scrittura e comprensione dei comandi in lingua inglese.' },
        { step: '5', title: 'Simulazione d’Udienza', desc: 'Colloquio di prova con dinamica di stress per ricreare le condizioni effettive.' },
        { step: '6', title: 'Risoluzione Errori', desc: 'Eliminazione di discrepanze tra documenti depositati e dichiarazioni verbali.' },
        { step: '7', title: 'Allineamento Finale', desc: 'Calibrazione sartoriale in base allo storico personale del cliente.' },
      ],
    },
    about: {
      title1: 'Soluzioni Giuridiche',
      title2: 'ad Alta Precisione',
      desc: 'Pratica legale privata per vertenze transfrontaliere complesse negli Stati Uniti e nei poli finanziari internazionali. Padronanza del diritto federale, pianificazione strategica e tutela dell’assistito.',
      p1Title: '15+ anni negli USA',
      p1Desc: 'Profonda competenza in diritto federale e procedure USCIS. Status personale di cittadino statunitense.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Segreto Professionale',
      p2Desc: 'Riservatezza istituzionale garantita dall’Attorney-Client Privilege. Tutela assoluta di dati e beni.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Integrazione Giurisdizionale',
      p3Desc: 'Coordinamento societario: USA (Delaware, Wyoming), UE, Regno Unito ed EAU (DIFC). Disinnesco dei conflitti di legge.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Metodo Analyze → Act',
      p4Desc: 'Analisi preventiva dei rischi prima dell’invio di qualsiasi documentazione ufficiale.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'I principi della nostra pratica',
    },
    countries: {
      badge: 'GEOGRAFIA E ORDINAMENTI GIURIDICI',
      title1: 'Giurisdizioni Internazionali',
      title2: 'd’Intervento',
      desc: 'Competenze multidisciplinari al crocevia tra Common Law e Civil Law. Sincronizziamo gli strumenti processuali per proteggere i vostri diritti.',
      btnAll: 'Tutte le giurisdizioni',
      hub1Name: 'Stati Uniti',
      hub1Badge: 'Focus Primario',
      hub1System: 'Diritto Federale USA e Statale',
      hub1Desc: 'Pratiche di immigrazione (EB-1A / NIW / Cittadinanza), diritto societario del Delaware e Wyoming, contenzioso federale.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'EAU (DIFC / ADGM)',
      hub2Badge: 'Hub Finanziario',
      hub2System: 'DIFC Courts e English Common Law',
      hub2Desc: 'Holding internazionali, trasferimento di patrimoni, family office e protezione dei capitali a Dubai.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'Regno Unito',
      hub3Badge: 'Diritto Inglese',
      hub3System: 'English Common Law',
      hub3Desc: 'Contratti commerciali secondo il diritto inglese, arbitrato londinese e trust transfrontalieri.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'Unione Europea (UE)',
      hub4Badge: 'Diritto Comunitario',
      hub4System: 'Civil Law e Regolamenti UE',
      hub4Desc: 'Assistenza legale in Germania, Francia, Cipro e Spagna. Compliance societaria e gestione dei rischi sanzionatori.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'CORRIDOIO:',
    },
    cases: {
      badge: 'CASI STUDIO E RISULTATI',
      title: 'Casi Risolti',
      desc: 'Dossier anonimizzati: valutazione del rischio, strategia processuale ed esito positivo vincolante.',
      btnAll: 'Tutti i casi studio',
      problemLabel: 'CRITICITÀ LEGALE:',
      solutionLabel: 'STRATEGIA PROCESSUALE:',
      resultLabel: 'RISULTATO CONSEGUITO:',
      similarSituation: 'Ha una situazione simile?',
    },
    faq: {
      badge: 'TRASPARENZA E STANDARDS',
      title: 'Domande frequenti',
      desc: 'Dettagli su modalità operative, giurisdizioni e pagamenti.',
    },
    contacts: {
      badge: 'CONTATTO DIRETTO',
      title: 'Contatta lo Studio',
      desc: 'L’analisi iniziale è coperta da segreto professionale. Selezioni il canale preferito.',
      scheduleTitle: 'Orari di Attività',
      scheduleDesc: 'Lunedì — Venerdì: 09:00 – 20:00 (EST). Emergenze clienti convenzionati: 24/7.',
      tgTitle: 'Bot Telegram Protetto',
      tgDesc: 'Valutazione rapida e invio sicuro della documentazione.',
      btnModal: 'Richiedi analisi del caso',
    },
    footer: {
      slogan: 'I vostri diritti — senza frontiere.',
      disclaimer: 'Le informazioni contenute nel presente sito hanno valore puramente informativo. La riservatezza è assicurata dal segreto professionale Attorney-Client Privilege Rule 1.6.',
      rights: 'Tutti i diritti riservati.',
      navTitle: 'Navigazione',
      contactsTitle: 'Contatti',
    },
  },

  // ===========================================================================
  // FRENCH (FR)
  // ===========================================================================
  fr: {
    nav: {
      services: 'Services',
      usaGreenCard: 'USA & GREEN CARD',
      jurisdictions: 'Juridictions',
      cases: 'Dossiers',
      about: 'Le Cabinet',
      faq: 'Questions',
      contacts: 'Contact',
      bookConsultation: 'Consultation',
      langTitle: 'Langue / Language',
    },
    hero: {
      badge: 'CONSEIL JURIDIQUE INTERNATIONAL',
      title1: 'Vos droits —',
      title2: 'sans frontières',
      desc: 'Conseil juridique de haut niveau et défense institutionnelle pour particuliers et entreprises aux États-Unis et à l’international. Situation complexe → analyse chirurgicale → stratégie → solution protégée.',
      badgeNy: '15 ans à New York',
      badgeCitizen: 'Citoyen américain',
      ctaConsultation: 'ANALYSER MA SITUATION',
      fastContact: 'Contact direct via Telegram',
      stat1Num: '15+ Ans',
      stat1Title: 'à New York',
      stat1Desc: 'environnement juridique américain',
      stat2Num: 'U.S. Citizen',
      stat2Title: 'Citoyen américain',
      stat2Desc: 'connaissance intime de l’USCIS',
      stat3Num: 'International',
      stat3Title: 'Dossiers Transfrontaliers',
      stat3Desc: 'USA · Europe · EAU · Monde',
      stat4Num: '100%',
      stat4Title: 'Confidentialité',
      stat4Desc: 'Secret professionnel strict (NDA)',
    },
    services: {
      tag: 'SOLUTIONS GLOBALES',
      title1: 'Solutions juridiques stratégiques',
      title2: 'sans modèles préconçus',
      desc: 'V. I. LEVIN est un cabinet privé accompagnant particuliers et entreprises confrontés à des enjeux complexes aux États-Unis ou dans plusieurs juridictions.',
      btnAll: 'Tous les domaines d’intervention',
      cardAction: 'Explorer le domaine',
      flagshipBadge: 'Phare',
      items: [
        {
          num: '01',
          code: 'US IMMIGRATION & STATUS',
          title: 'USA : Green Card, EB-1A / NIW & Citoyenneté',
          desc: 'Stratégie personnalisée d’obtention de la résidence permanente américaine : visas de talents EB-1A, dispense d’intérêt national EB-2 NIW, changement de statut et naturalisation.',
          href: '/usa/green-card',
          highlight: true,
        },
        {
          num: '02',
          code: 'CORPORATE & CROSS-BORDER',
          title: 'Affaires Internationales et Contrats Transfrontaliers',
          desc: 'Structuration sociétaire aux USA (Delaware, Wyoming), au Royaume-Uni, dans l’UE et aux EAU (DIFC). Contrats transnationaux et conformité.',
          href: '/services/business',
        },
        {
          num: '03',
          code: 'PRIVATE WEALTH & TRUSTS',
          title: 'Protection Patrimoniale Privée, Fonds et Trusts',
          desc: 'Mise en place de trusts internationaux irrévocables, immunisation des actifs contre les tiers et protection fiscale internationale.',
          href: '/services/legal-consultation',
        },
        {
          num: '04',
          code: 'DISPUTES & ARBITRATION',
          title: 'Contentieux Transfrontaliers et Arbitrage Commercial',
          desc: 'Représentation dans les litiges commerciaux internationaux, arbitrage institutionnel et exécution transfrontalière de jugements.',
          href: '/services/representation',
        },
        {
          num: '05',
          code: 'RISK AUDIT & COMPLIANCE',
          title: 'Audit des Risques Juridiques et Due Diligence',
          desc: 'Examen juridique rigoureux ligne par ligne avant signature : identification des clauses à risque et audit des dossiers migratoires.',
          href: '/services/legal-consultation',
        },
        {
          num: '06',
          code: 'STRATEGIC COUNSEL',
          title: 'Stratégie Juridique Internationale Sur-Mesure',
          desc: 'Accompagnement juridique pour problématiques atypiques à l’articulation du droit fédéral américain et des droits étrangers.',
          href: '/contacts',
        },
      ],
    },
    greencard: {
      badge: 'PRATIQUE STRATÉGIQUE MAJEURE',
      title1: 'USA : Immigration, Citoyenneté',
      title2: '& Défense du Statut',
      desc: 'Ni "cours de soutien" ni formulaires standardisés. Nous préparons au processus d’adjudication américain avec une parfaite maîtrise du système USCIS.',
      btnEvaluate: 'Évaluer mes chances Green Card',
      btnTelegram: 'Audit Telegram',
      cardAction: 'En savoir plus',
      cards: [
        {
          code: 'GREEN CARD',
          title: 'Green Card & Immigration',
          desc: 'Stratégie sur-mesure pour la résidence permanente : EB-1A talents, EB-2 NIW, changement de statut et regroupement familial.',
          tag: 'Prisé',
        },
        {
          code: 'CITIZENSHIP',
          title: 'Citoyenneté Américaine',
          desc: 'Accompagnement juridique intégral jusqu’à la prestation de serment et la délivrance du passeport US.',
          tag: 'Phare',
        },
        {
          code: 'CIVICS TEST',
          title: 'Test Civique 2026',
          desc: 'Préparation à l’examen officiel 2026 de 128 questions : histoire des États-Unis, Constitution, institutions et prérequis d’anglais.',
          tag: 'Test 2026',
        },
        {
          code: 'INTERVIEW',
          title: 'Préparation à l’Entretien USCIS',
          desc: 'Simulations rigoureuses en conditions réelles d’audition : typologie des questions, formulation des réponses et levée de doutes.',
          tag: 'Simulation',
        },
        {
          code: 'N-400 AUDIT',
          title: 'Audit de la Demande N-400',
          desc: 'Examen juridique ligne par ligne du dossier de naturalisation avant transmission pour écarter tout motif de rejet.',
          tag: 'Audit Risques',
        },
        {
          code: 'STRATEGY',
          title: 'Stratégie & Diagnostic Sur-Mesure',
          desc: 'Évaluation personnalisée des chances de succès pour la résidence ou citoyenneté avec sécurisation des points de friction.',
          tag: 'Sur-Mesure',
        },
      ],
      methodologyBadge: 'MÉTHODOLOGIE EXCLUSIVE DE PRÉPARATION',
      methodologyTitle: '7 étapes de préparation à la citoyenneté américaine',
      methodologyDesc: 'Non un simple apprentissage par cœur, mais une levée méthodique de toute vulnérabilité avant l’examen USCIS.',
      stages: [
        { step: '1', title: 'Analyse N-400', desc: 'Analyse ligne par ligne pour corriger toute irrégularité avant soumission.' },
        { step: '2', title: 'Questions de l’Officier', desc: 'Maîtrise des angles d’interrogation de l’officier et réponses juridiquement sécurisées.' },
        { step: '3', title: 'Examen Civique 2026', desc: 'Entraînement approfondi sur les 128 questions d’histoire et d’institutions des USA.' },
        { step: '4', title: 'Composante Anglaise', desc: 'Perfectionnement sur l’expression, la lecture et la compréhension des directives officielles.' },
        { step: '5', title: 'Entretien Blanc', desc: 'Simulation complète d’audience sous conditions de stress reproduisant l’audition USCIS.' },
        { step: '6', title: 'Correction des Faiblesses', desc: 'Élimination des incohérences susceptibles de motiver un avis défavorable.' },
        { step: '7', title: 'Ajustement Stratégique', desc: 'Alignement final personnalisé en fonction du profil spécifique du candidat.' },
      ],
    },
    about: {
      title1: 'Solutions Juridiques',
      title2: 'de Haute Précision',
      desc: 'Pratique privée dédiée aux dossiers complexes aux États-Unis et dans les grands centres financiers internationaux. Maîtrise du système fédéral, stratégie innovante et protection sans faille des intérêts du client.',
      p1Title: '15+ ans d’expérience aux USA',
      p1Desc: 'Expertise approfondie en droit fédéral et réglementation USCIS. Citoyenneté américaine personnelle.',
      p1Note: 'USCIS · Federal Courts · U.S. Citizen',
      p2Title: 'Secret Professionnel',
      p2Desc: 'Confidentialité institutionnelle régie par l’Attorney-Client Privilege. Protection intégrale des documents et avoirs.',
      p2Note: 'Attorney-Client Privilege · Rule 1.6',
      p3Title: 'Coordination Juridictionnelle',
      p3Desc: 'Structuration transfrontalière : USA (Delaware, Wyoming), UE, Royaume-Uni et EAU (DIFC). Résorption des conflits de lois.',
      p3Note: 'USA · EU · UK · UAE (DIFC)',
      p4Title: 'Méthode Analyze → Act',
      p4Desc: 'Audit préventif approfondi des risques avant le dépôt formel de toute procédure.',
      p4Note: 'Pre-filing risk audit · Zero reject strategy',
      linkMore: 'Découvrir les principes du cabinet',
    },
    countries: {
      badge: 'GÉOGRAPHIE ET SYSTÈMES JURIDIQUES',
      title1: 'Juridictions Internationales',
      title2: 'd’Intervention',
      desc: 'Compétences transversales au carrefour de la Common Law et du Droit Civil. Nous harmonisons les règles de procédure de multiples pays.',
      btnAll: 'Toutes les juridictions',
      hub1Name: 'États-Unis',
      hub1Badge: 'Foyer Principal',
      hub1System: 'Droit Fédéral & Droit des États Américains',
      hub1Desc: 'Immigration (EB-1A / NIW / Citoyenneté), droit des sociétés au Delaware et Wyoming, contentieux fédéral et défense de statut.',
      hub1Corridor: 'NY · DE · FL · CA',
      hub2Name: 'EAU (DIFC / ADGM)',
      hub2Badge: 'Hub International',
      hub2System: 'DIFC Courts & English Common Law',
      hub2Desc: 'Holdings internationales, transfert de capitaux, family offices et protection d’actifs dans la zone financière de Dubaï.',
      hub2Corridor: 'Dubai · Abu Dhabi',
      hub3Name: 'Royaume-Uni',
      hub3Badge: 'Droit Anglais',
      hub3System: 'English Common Law',
      hub3Desc: 'Contrats commerciaux régis par le droit anglais, arbitrage à Londres et trusts transfrontaliers.',
      hub3Corridor: 'London · Common Law',
      hub4Name: 'Union Européenne (UE)',
      hub4Badge: 'Droit Européen',
      hub4System: 'Droit Civil & Règlements UE',
      hub4Desc: 'Accompagnement juridique en Allemagne, France, à Chypre et en Espagne. Conformité et conformité aux sanctions.',
      hub4Corridor: 'DE · FR · CY · ES',
      corridorLabel: 'CORRIDOR :',
    },
    cases: {
      badge: 'PRATIQUE & RÉSULTATS',
      title: 'Cas Pratiques Réels',
      desc: 'Dossiers anonymisés : analyse de risques, stratégie procédurale sur-mesure et résultats obtenus.',
      btnAll: 'Consulter tous les cas',
      problemLabel: 'PROBLÉMATIQUE JURIDIQUE :',
      solutionLabel: 'STRATÉGIE & DÉNOUEMENT :',
      resultLabel: 'RÉSULTAT HOMOLOGUÉ :',
      similarSituation: 'Vous avez une situation similaire ?',
    },
    faq: {
      badge: 'TRANSPARENCE & STANDARDS',
      title: 'Questions fréquentes',
      desc: 'Réponses claires sur le cadre d’intervention, les juridictions et les règlements.',
    },
    contacts: {
      badge: 'CONTACT DIRECT',
      title: 'Contacter le Cabinet',
      desc: 'La première analyse est réalisée sous strict secret professionnel. Choisissez votre canal de communication.',
      scheduleTitle: 'Horaires d’Ouverture',
      scheduleDesc: 'Lundi — Vendredi : 09h00 – 20h00 (EST). Urgences clients sous contrat : 24h/24.',
      tgTitle: 'Bot Sécurisé Telegram',
      tgDesc: 'Qualification rapide et transmission chiffrée de documents.',
      btnModal: 'Demander l’étude du dossier',
    },
    footer: {
      slogan: 'Vos droits — sans frontières.',
      disclaimer: 'Les informations présentées sur ce site sont fournies à titre indicatif uniquement. Confidentialité garantie selon la règle Rule 1.6 de l’Attorney-Client Privilege.',
      rights: 'Tous droits réservés.',
      navTitle: 'Navigation',
      contactsTitle: 'Contact',
    },
  },
};

interface LanguageContextType {
  currentLang: LanguageCode;
  setLanguage: (code: LanguageCode) => void;
  t: (section: string, key: string) => string;
  dict: any;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLang, setCurrentLang] = useState<LanguageCode>('ru');

  useEffect(() => {
    try {
      const savedLang = localStorage.getItem('v_levin_lang') as LanguageCode;
      if (savedLang && ['ru', 'uk', 'en', 'es', 'it', 'fr'].includes(savedLang)) {
        setCurrentLang(savedLang);
      }
    } catch {
      // ignore
    }
  }, []);

  const setLanguage = (code: LanguageCode) => {
    setCurrentLang(code);
    try {
      localStorage.setItem('v_levin_lang', code);
    } catch {
      // ignore
    }
  };

  const dict = TRANSLATIONS[currentLang] || TRANSLATIONS.ru;

  const t = (section: string, key: string): string => {
    const sec = dict[section];
    if (sec && sec[key]) {
      return sec[key];
    }
    const fallbackSec = TRANSLATIONS.ru[section];
    if (fallbackSec && fallbackSec[key]) {
      return fallbackSec[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, dict }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
